# Generated by Django 6.0.3 on 2026-03-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='is_booking_enabled',
            field=models.BooleanField(default=True, help_text='Master can pause bookings without deactivating profile'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', help_text='IANA timezone string, e.g. Europe/Moscow', max_length=50),
        ),
    ]
