# Generated by Django 6.0.3 on 2026-04-08 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_specialistprofile_is_booking_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Anonymous (guest) user created on first app launch without registration'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='User has completed the onboarding flow (name + location saved)'),
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(db_index=True, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anonymous Session',
                'verbose_name_plural': 'Anonymous Sessions',
                'indexes': [models.Index(fields=['device_id'], name='users_anony_device__6af618_idx'), models.Index(fields=['expires_at'], name='users_anony_expires_ff9353_idx')],
            },
        ),
    ]
