# Generated by Django 5.2.5 on 2026-04-25 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_guest_onboarding_anonymoussession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='specialists/portfolio/')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='users.specialistprofile')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['specialist', 'sort_order'], name='users_speci_special_1de79f_idx')],
            },
        ),
    ]
