# Generated by Django 5.2.5 on 2026-04-27 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialistportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_districts', models.JSONField(blank=True, default=list, help_text='Список названий районов / станций метро где удобно записываться. Mobile shows top-3, full list in profile.')),
                ('preferred_time_slots', models.JSONField(blank=True, default=list, help_text='Список ключей TimeSlot — какие окна удобнее. Validated in serializer against TimeSlot choices.')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diet_type', models.CharField(blank=True, choices=[('omnivore', 'Всеядное'), ('vegetarian', 'Вегетарианство'), ('vegan', 'Веганство'), ('keto', 'Кето'), ('halal', 'Халяль'), ('kosher', 'Кошер'), ('other', 'Другое')], default='', max_length=20)),
                ('skin_sensitivities', models.JSONField(blank=True, default=list, help_text='Free-form list of allergens / sensitivities (no clinical diagnosis — just user-stated preferences for vendors).')),
                ('prefers_flexible_cancellation', models.BooleanField(default=False, help_text='If True, AI Chat softly biases toward specialists with lenient cancellation policies (Phase 6 hookup).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Personal Context',
                'verbose_name_plural': 'User Personal Contexts',
            },
        ),
    ]
