# Generated by Django 5.2.5 on 2026-03-19 14:23

from django.db import migrations


def populate_phones(apps, schema_editor):
    """Set placeholder phone for users with NULL phone."""
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(phone__isnull=True):
        user.phone = f"+7legacy{user.pk:06d}"
        user.save(update_fields=['phone'])


def reverse_populate(apps, schema_editor):
    """Revert placeholder phones back to NULL."""
    User = apps.get_model('users', 'User')
    User.objects.filter(phone__startswith='+7legacy').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_otpcode_is_verified_phone_unique"),
    ]

    operations = [
        migrations.RunPython(populate_phones, reverse_populate),
    ]
