# Generated by Django 5.2.5 on 2026-04-29 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpersonalcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSpecialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.specialistprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_specialists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Specialist',
                'verbose_name_plural': 'Favorite Specialists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_favor_user_id_067081_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'specialist'), name='unique_favorite_per_user_specialist')],
            },
        ),
    ]
