# Generated by Django 5.2.5 on 2026-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_make_phone_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("specialist", "Specialist"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
