# Generated by Django 5.2.5 on 2026-05-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_specialist_tenant_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalcontext',
            name='busy_days',
            field=models.JSONField(blank=True, default=list, help_text="List of ISO weekday short names ('mon','tue',...) when the user almost never books — inferred from no-bookings history."),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='data_sources',
            field=models.JSONField(blank=True, default=dict, help_text="Per-field provenance: 'explicit' (user typed), 'inferred' (Celery task), 'signal' (Claude extraction). Drives transparency UI."),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='favorite_masters',
            field=models.JSONField(blank=True, default=list, help_text='List of SpecialistProfile.id (UUID strings) the user rebooked at least 3× — populated by infer_user_patterns (separate PR). Cross-domain engine boosts these.'),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='home_district',
            field=models.CharField(blank=True, default='', help_text='Free-form district / metro station near home. Bias for weekend / late-evening slots.', max_length=80),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='last_asked_at',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field timestamp of the last time AI asked. 24h cooldown rule reads this.'),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='min_rating_preference',
            field=models.FloatField(blank=True, help_text='Minimum specialist rating the user accepts (0.0-5.0). AI Chat filters catalog by this.', null=True),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='skipped_questions',
            field=models.JSONField(blank=True, default=dict, help_text='Anti-spam tracking: per-field {count:int, last_at:isoformat}. Skip × 2 → 30-day pause.'),
        ),
        migrations.AddField(
            model_name='userpersonalcontext',
            name='workplace_district',
            field=models.CharField(blank=True, default='', help_text="Free-form city district / metro station near the user's workplace. Used by AI Chat to bias 'after work' suggestions.", max_length=80),
        ),
    ]
