# Generated by Django 5.2.5 on 2026-05-07 04:02 — DRF-242.7
"""Composite tenant-prefixed indexes on User and SpecialistProfile.

Tenant-first scoping is the dominant access pattern for both surfaces;
without these indexes the planner falls back to global table scans plus
app-side tenant filter, which scales linearly with row count.

User: (tenant, is_active), (tenant, role) — auth list endpoints.
SpecialistProfile: (tenant, status), (tenant, is_available) — Pro app
verification queue and active masters list.

Pure additive — no schema rewrites, safe to apply online. On Postgres
prod tables with significant volume, prefer CREATE INDEX CONCURRENTLY
(handled separately if rows >100k).
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_tenants_ten_is_acti_2c1ec7_idx_tenants_ten_is_acti_c80453_idx'),
        ('users', '0009_personal_context_drf230'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['tenant', 'status'], name='sp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['tenant', 'is_available'], name='sp_tenant_available_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'is_active'], name='user_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role'], name='user_tenant_role_idx'),
        ),
    ]
