# Generated by Django 5.2.5 on 2026-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_specialistprofile_yookassa_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialistprofile",
            name="yclients_staff_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="YClients per-master staff id — required when booking_source='yclients' and the admin mini-app needs to resolve YClients staff ids → SpecialistProfile rows. Empty otherwise.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="busy_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="ISO weekday short names ('mon','tue',...) the user avoids.",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="data_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field provenance: explicit / inferred / signal.",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="favorite_masters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of SpecialistProfile.id strings rebooked >=3 times.",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="home_district",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-form district / metro station near home.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="last_asked_at",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field last-asked timestamp for 24h cooldown.",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="min_rating_preference",
            field=models.FloatField(
                blank=True, help_text="Minimum specialist rating (0.0-5.0).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="skipped_questions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field {count:int, last_at:isoformat}. Skip x2 -> pause.",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="workplace_district",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-form district / metro station near workplace.",
                max_length=80,
            ),
        ),
    ]
