# Generated by Django 5.2.5 on 2026-08-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_specialistprofile_yclients_staff_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linked_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Phase C proxy→real binding: set on a proxy row, points at the real account this external identity is bound to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_proxies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_proxy=True)
                    | models.Q(linked_user__isnull=True)
                ),
                name="user_linked_user_only_proxy",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(linked_user__isnull=True)
                    | ~models.Q(linked_user=models.F("id"))
                ),
                name="user_linked_user_not_self",
            ),
        ),
    ]
