# Generated by Django 5.2.5 on 2026-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_linked_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(
                default=False,
                help_text="Ayla platform operator: may administer any tenant, but only one explicitly addressed per request. Not a Django superuser.",
            ),
        ),
    ]
