# Generated by Django 5.2.5 on 2026-09-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_drf1062_platform_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingExternalIdentity",
            fields=[],
            options={
                "verbose_name": "внешняя личность без связи с Ayla",
                "verbose_name_plural": "Внешние личности без связи с Ayla (ждут оператора)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
