# Generated by Django 5.2.5 on 2026-09-11 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_pendingexternalidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DELETION_REQUESTED", "Запрошено"),
                            ("DELETION_PROCESSING", "Выполняется"),
                            ("DELETION_COMPLETED", "Завершено"),
                            ("DELETION_FAILED", "Сбой исполнителя"),
                        ],
                        default="DELETION_REQUESTED",
                        max_length=32,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("deadline_at", models.DateTimeField(editable=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("initiator", models.CharField(max_length=32)),
                ("steps", models.JSONField(blank=True, default=dict)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на удаление",
                "verbose_name_plural": "Заявки на удаление",
                "ordering": ["-requested_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                (
                                    "DELETION_REQUESTED",
                                    "DELETION_PROCESSING",
                                    "DELETION_FAILED",
                                ),
                            )
                        ),
                        fields=("user",),
                        name="deletionrequest_one_open_per_user",
                    )
                ],
            },
        ),
    ]
