# Generated by Django 5.2.5 on 2026-09-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_service_location"),
        ("users", "0018_pendingexternalidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistprofile",
            name="works_at",
            field=models.ForeignKey(
                blank=True,
                help_text="Место оказания услуг (§9). Для мастера салона — место этого салона; для самостоятельного — его собственная точка. Пусто — расстояние до мастера неизвестно, не ноль.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="masters",
                to="tenants.servicelocation",
            ),
        ),
    ]
