# Generated by Django 5.2.5 on 2026-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_specialistprofile_works_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistprofile",
            name="provisioned_external_user_id",
            field=models.CharField(
                blank=True,
                help_text="Внешний id бота, для которого заведён DRAFT-профиль (solo provisioning). Провенанс, не личность.",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
