# Generated by Django 5.2.5 on 2026-09-15 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_drf1828_provisioned_external_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistPublicationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command_id", models.UUIDField(unique=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("submitted", "Отправлен на проверку"),
                            ("already_pending", "Уже на проверке"),
                            ("already_active", "Уже опубликован"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_requests",
                        to="users.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["specialist", "created_at"],
                        name="pubreq_spec_created_idx",
                    )
                ],
            },
        ),
    ]
