# Generated by Django 5.2.5 on 2026-09-15 21:58

import users.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_drf1796_specialistpublicationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialistprofile",
            name="timezone",
            field=models.CharField(
                default="Europe/Moscow",
                help_text="IANA timezone string, e.g. Europe/Moscow",
                max_length=50,
                validators=[users.timezones.validate_iana_timezone],
            ),
        ),
    ]
