# Generated by Django 5.2.5 on 2026-09-18 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_drf1803_place_kind_note_service_area"),
        ("users", "0023_alter_specialistprofile_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalonAdminLinkRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("external_user_id", models.CharField(db_index=True, max_length=200)),
                (
                    "actor",
                    models.CharField(
                        help_text="Operator label from the bot's Django Admin (no name, no phone).",
                        max_length=200,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("result", models.CharField(default="created", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salon_admin_link_requests",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The FRESH salon-administrator account this request created.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salon_admin_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon admin link request",
                "verbose_name_plural": "Salon admin link requests",
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="salonadminlink_tenant_idx",
                    )
                ],
            },
        ),
    ]
