# Generated by Django 5.2.5 on 2026-09-24 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_drf2085_salonadminlinkrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistIdentityLinkRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("external_user_id", models.CharField(db_index=True, max_length=200)),
                (
                    "actor",
                    models.CharField(
                        help_text="Caller label (e.g. `bot:onboarding_accept`) — no name, no phone.",
                        max_length=200,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("result", models.CharField(default="created", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="The specialist profile whose identity edge this request created.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_link_requests",
                        to="users.specialistprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specialist's working account the identity was bound to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specialist_identity_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Specialist identity link request",
                "verbose_name_plural": "Specialist identity link requests",
                "indexes": [
                    models.Index(
                        fields=["profile", "created_at"], name="specidlink_profile_idx"
                    )
                ],
            },
        ),
    ]
