# Generated by Django 5.2.5 on 2026-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_drf2442_specialistidentitylinkrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_test_persona",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Тестовая личность: видит демонстрационные салоны (`Tenant.is_demo`). Ставится владельцем для показа и съёмки эталонов. Не имеет отношения к `is_proxy` — тот стоит у всех внешних личностей, включая живых клиентов бота.",
            ),
        ),
    ]
