# Generated by Django 5.2.5 on 2026-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_drf2420_demo_and_test_persona"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deletionrequest",
            name="deletionrequest_one_open_per_user",
        ),
        migrations.AddField(
            model_name="deletionrequest",
            name="bot_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="deletionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DELETION_REQUESTED", "Запрошено"),
                    ("DELETION_PROCESSING", "Выполняется"),
                    ("DELETION_COMPLETED", "Завершено"),
                    ("DELETION_FAILED", "Сбой исполнителя"),
                    ("DELETION_STALLED", "Остановлено: бот не подтверждает"),
                ],
                default="DELETION_REQUESTED",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "DELETION_REQUESTED",
                            "DELETION_PROCESSING",
                            "DELETION_FAILED",
                            "DELETION_STALLED",
                        ),
                    )
                ),
                fields=("user",),
                name="deletionrequest_one_open_per_user",
            ),
        ),
    ]
