# Generated by Django 5.2.5 on 2026-10-05 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_drf2644_stalled_and_bot_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentEventReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("consent_type", models.CharField(max_length=40)),
                ("granted", models.BooleanField()),
                ("granted_at", models.DateTimeField()),
                (
                    "granted_via",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("applied", "Применено"),
                            ("duplicate", "Повтор"),
                            ("ignored", "Тип каталогу не нужен"),
                            ("stale", "Старше известного"),
                            ("no_subject", "Человек каталогу не известен"),
                        ],
                        max_length=16,
                    ),
                ),
                ("erased", models.JSONField(blank=True, default=list)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_event_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_type", models.CharField(max_length=40)),
                ("granted", models.BooleanField()),
                ("granted_at", models.DateTimeField()),
                ("event_id", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "consent_type"),
                        name="consentstate_user_type_uniq",
                    )
                ],
            },
        ),
    ]
