# Generated by Django 5.2.5 on 2026-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_drf2776_consent_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuserrelationship",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("receptionist", "Receptionist"),
                ],
                default="customer",
                help_text="customer: granted on booking via Variant E. staff: specialist working in the salon. admin: tenant owner / manager. receptionist: front desk of one salon — bookings, not settings (DRF-2826).",
                max_length=16,
            ),
        ),
    ]
