# Generated by Django 5.2.5 on 2026-10-06 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_drf2826_receptionist_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "practitioner_class",
                    models.CharField(
                        choices=[
                            ("cosmetic_esthetician", "Косметик-эстетист"),
                            ("nurse_cosmetology", "Медсестра по косметологии"),
                            ("physician_cosmetologist", "Врач-косметолог"),
                            ("medical_specialist", "Врач-специалист"),
                            ("protocol_specific", "По протоколу"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "protocol_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ссылка на протокол — только для «По протоколу».",
                        max_length=200,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Основание проверки: какой документ сверен.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qualifications",
                        to="users.specialistprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто проверил квалификацию. Пусто — не проверена.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Квалификация мастера",
                "verbose_name_plural": "Квалификации мастеров",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("specialist", "practitioner_class", "protocol_ref"),
                        name="practitionerqualification_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "practitioner_class__in",
                                [
                                    "cosmetic_esthetician",
                                    "nurse_cosmetology",
                                    "physician_cosmetologist",
                                    "medical_specialist",
                                    "protocol_specific",
                                ],
                            )
                        ),
                        name="practitionerqualification_class_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("practitioner_class", "protocol_specific"),
                                models.Q(("protocol_ref", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(
                                    ("practitioner_class", "protocol_specific"),
                                    _negated=True,
                                ),
                                ("protocol_ref", ""),
                            ),
                            _connector="OR",
                        ),
                        name="practitionerqualification_protocol_ref_iff_protocol_specific",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("verified_by__isnull", True),
                                ("verified_at__isnull", True),
                                ("verification_source_ref", ""),
                            ),
                            models.Q(
                                ("verified_by__isnull", False),
                                ("verified_at__isnull", False),
                                models.Q(
                                    ("verification_source_ref", ""), _negated=True
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="practitionerqualification_verification_all_or_nothing",
                    ),
                ],
            },
        ),
    ]
