# Generated by Django 5.2.5 on 2026-07-19 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0011_b1_payment_vocab"),
        ("tenants", "0003_seed_default_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "subscription_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fees_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Выставлен"),
                            ("paid", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("canceled", "Отменён"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Инвойс",
                "verbose_name_plural": "Инвойсы",
            },
        ),
        migrations.CreateModel(
            name="TariffPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("solo", "Самостоятельный мастер"),
                            ("salon", "Салон (до 3 мастеров)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("max_masters", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
            },
        ),
        migrations.CreateModel(
            name="BillingPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("setup", "Привязка карты"),
                            ("recurrent", "Автосписание"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("succeeded", "Успешен"),
                            ("failed", "Ошибка"),
                            ("canceled", "Отменён"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                (
                    "confirmation_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.billinginvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж биллинга",
                "verbose_name_plural": "Платежи биллинга",
            },
        ),
        migrations.CreateModel(
            name="SpecialistSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Пробный период"),
                            ("active", "Активна"),
                            ("past_due", "Просрочена"),
                            ("canceled", "Отменена"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateField(blank=True, null=True)),
                ("current_period_end", models.DateField(blank=True, null=True)),
                (
                    "payment_method_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "payment_method_saved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_subscriptions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.tariffplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка специалиста",
                "verbose_name_plural": "Подписки специалистов",
            },
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="billing.specialistsubscription",
            ),
        ),
        migrations.CreateModel(
            name="BillingConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_version", models.CharField(max_length=40)),
                ("given_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие на автоплатёж",
                "verbose_name_plural": "Согласия на автоплатёж",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("user",),
                        name="billing_consent_single_active_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("period_start", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Начислен"),
                            ("invoiced", "Включён в инвойс"),
                            ("charged", "Оплачен"),
                            ("canceled", "Отменён"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_fee",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_fees",
                        to="billing.billinginvoice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_fees",
                        to="billing.specialistsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комиссия за запись",
                "verbose_name_plural": "Комиссии за записи",
                "indexes": [
                    models.Index(
                        fields=["subscription", "period_start", "status"],
                        name="bookingfee_charge_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="specialistsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("user",),
                name="billing_subscription_unique_personal",
            ),
        ),
        migrations.AddConstraint(
            model_name="specialistsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)),
                fields=("tenant",),
                name="billing_subscription_unique_tenant",
            ),
        ),
    ]
