# Generated by Django 5.2.5 on 2026-07-19

from django.db import migrations

# AYLA-DEC-0001: subscription 690₽/mo solo, 990₽/mo salon (up to 3 masters).
TARIFF_PLANS = [
    {
        "code": "solo",
        "name": "Самостоятельный мастер",
        "price": "690.00",
        "max_masters": 1,
    },
    {
        "code": "salon",
        "name": "Салон (до 3 мастеров)",
        "price": "990.00",
        "max_masters": 3,
    },
]


def seed_tariff_plans(apps, schema_editor):
    TariffPlan = apps.get_model("billing", "TariffPlan")
    for plan in TARIFF_PLANS:
        TariffPlan.objects.get_or_create(code=plan["code"], defaults=plan)


def unseed_tariff_plans(apps, schema_editor):
    TariffPlan = apps.get_model("billing", "TariffPlan")
    TariffPlan.objects.filter(code__in=[p["code"] for p in TARIFF_PLANS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_tariff_plans, unseed_tariff_plans),
    ]
