# Generated by Django 5.2.5 on 2026-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_seed_tariff_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistsubscription",
            name="card_brand",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="specialistsubscription",
            name="card_last4",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
