# Generated by Django 5.2.5 on 2026-08-19 07:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_key",
                    models.SlugField(
                        blank=True,
                        help_text="Ключ курируемой цели (GoalOption.key); NULL при свободном вводе",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "goal_text",
                    models.TextField(
                        blank=True,
                        help_text="Дословный свободный ввод пользователя; не нормализуется",
                        null=True,
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source_channel",
                    models.CharField(
                        choices=[("bot", "Бот (DM)"), ("miniapp", "Mini App")],
                        help_text="Канал, в котором цель выбрана (бот ↔ Mini App; цель переживает смену канала)",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-selected_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "is_active"],
                        name="clientgoal_client_active_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("goal_key__isnull", False),
                            ("goal_text__isnull", False),
                            _connector="OR",
                        ),
                        name="clientgoal_key_or_text_present",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("client",),
                        name="clientgoal_one_active_per_client",
                    ),
                ],
            },
        ),
    ]
