# Generated by Django 5.2.5 on 2026-09-03 11:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalAnketaRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_anketa_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Цель, которой завершился проход; NULL — проход брошен",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anketa_runs",
                        to="goals.clientgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalAnketaAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_key", models.SlugField(max_length=32)),
                (
                    "option_key",
                    models.SlugField(
                        blank=True,
                        help_text="Ключ выбранного варианта; NULL при свободном вводе",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Дословный свободный ввод; не нормализуется",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="goals.goalanketarun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goalanketarun",
            index=models.Index(
                fields=["client", "completed_at"], name="goalanketarun_client_open_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="goalanketarun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed_at__isnull", True)),
                fields=("client",),
                name="goalanketarun_one_open_per_client",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalanketaanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("option_key__isnull", False),
                    ("answer_text__isnull", False),
                    _connector="OR",
                ),
                name="goalanketaanswer_option_or_text_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalanketaanswer",
            constraint=models.UniqueConstraint(
                fields=("run", "step_key"), name="goalanketaanswer_one_per_step"
            ),
        ),
    ]
