# Generated by Django 5.2.5 on 2026-09-04 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goalanketarun_goalanketaanswer_and_more"),
        ("tenants", "0003_seed_default_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientgoal",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Салон, в контексте которого цель названа; NULL — салон неизвестен",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_goals",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="clientgoal",
            index=models.Index(
                fields=["tenant", "is_active"], name="clientgoal_tenant_active_idx"
            ),
        ),
    ]
