# Generated by Django 5.2.5 on 2026-09-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0006_clientgoal_state_lifecycle"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="goalanketaanswer",
            name="goalanketaanswer_option_or_text_present",
        ),
        migrations.AddField(
            model_name="goalanketaanswer",
            name="option_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ключи отмеченных вариантов (режим multi); [] у остальных",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalanketaanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("option_key__isnull", False),
                    ("answer_text__isnull", False),
                    models.Q(("option_keys", []), _negated=True),
                    _connector="OR",
                ),
                name="goalanketaanswer_option_or_text_present",
            ),
        ),
    ]
