# Generated by Django 5.2.5 on 2026-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0007_anketaanswer_option_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientgoal",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Срок цели, названный клиентом; NULL — без срока (умолчание)",
                null=True,
            ),
        ),
    ]
