# Generated by Django 5.2.5 on 2026-09-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0008_clientgoal_target_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientgoal",
            name="text_origin",
            field=models.CharField(
                blank=True,
                choices=[("user_stated", "Слова человека")],
                default="",
                help_text="user_stated — слова человека; пусто — происхождение не установлено",
                max_length=16,
            ),
        ),
    ]
