# Generated by Django 5.2.5 on 2026-05-05 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, help_text='Validated against analytics.event_catalogue.EVENT_NAMES.', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('anonymous_session_id', models.UUIDField(blank=True, db_index=True, help_text='Set when actor is NULL (welcome / pre-OTP flow).', null=True)),
                ('app_type', models.CharField(choices=[('client', 'Ayla (client)'), ('pro', 'Ayla Pro (specialist)')], db_index=True, help_text='Mirrors X-App-Type header — events from Pro app vs client app are first-class separate streams.', max_length=8)),
                ('client_event_id', models.UUIDField(help_text='UUID generated client-side; (actor, client_event_id) is unique so retries are safe.')),
                ('client_timestamp', models.DateTimeField(blank=True, help_text='Mobile-side timestamp at emission. Trust-but-verify; use server `created_at` for cohort analysis.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='NULL for anonymous emissions (anonymous_session_id carries the session instead).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Denormalised from request.tenant; allows a future dashboard to scope events per tenant. Nullable for single-tenant rollout phase.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', '-created_at'], name='analytics_a_event_n_9332fe_idx'), models.Index(fields=['actor', '-created_at'], name='analytics_a_actor_i_03785e_idx'), models.Index(fields=['tenant', 'event_name', '-created_at'], name='analytics_a_tenant__0557ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('actor__isnull', False)), fields=('actor', 'client_event_id'), name='analytics_event_unique_per_actor'), models.UniqueConstraint(condition=models.Q(('anonymous_session_id__isnull', False)), fields=('anonymous_session_id', 'client_event_id'), name='analytics_event_unique_per_anon_session')],
            },
        ),
    ]
