# Generated by Django 5.2.5 on 2026-05-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_ten_is_acti_c80453_idx',
            old_name='tenants_ten_is_acti_2c1ec7_idx',
        ),
    ]
