"""DRF-1662 — происхождение координат на Tenant (§139 от 11.09.2026).

Восемь колонок, все добавляемые: исходный и нормализованный адрес,
широта, долгота, провайдер, точность, статус, время геокодирования.

Миграция НЕ ТРОГАЕТ ДАННЫЕ. Ни ``RunPython``, ни ``RunSQL``, ни
``default`` с числом. Причины две:

1. Слияние есть выкладка. Миграция, меняющая данные, сработала бы на
   живых одиннадцати тенантах в момент слияния — не тогда, когда
   оператор решит её запустить.
2. Заполнять координаты нечем: адаптера геокодера ещё нет (§139 назвал
   Яндекс, но адаптер — отдельный тикет). Проставить числа «пока что»
   значило бы вернуть отменённое §137 умолчание.

Существующие строки получают ``geocode_status='not_attempted'`` и
``latitude/longitude = NULL`` — честное «геокодер сюда не приходил».
Заполнение — отдельной командой, позже.
"""
# Generated by Django 5.2.5 on 2026-09-11 05:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_address_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="geocode_normalized_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Адрес, каким его вернул провайдер (§139 «нормализованный адрес»). Показывать человеку при подтверждении неоднозначного адреса. Пусто = провайдер ничего не вернул.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="geocode_precision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Точность результата словарём провайдера (§139 «точность ... результата»); у Яндекса это exact/number/near/range/street/other. Словарь провайдерский намеренно: приводить его к общему виду — работа адаптера, которого здесь ещё нет, и приведение без адаптера потеряло бы исходный ответ. Пусто = провайдер точность не сообщил.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="geocode_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кто выдал координаты: ``yandex`` для пилота, ``manual`` для подтверждённых человеком. §139: провайдер в записи делает замену провайдера НАБЛЮДАЕМОЙ — без него координаты от двух сервисов лежат неразличимо. Пусто = координат нет.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="geocode_source_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Строка адреса ровно в том виде, в каком её отдали геокодеру. Хранится отдельно от ``address``, потому что ``address`` редактируем: без снимка входа нельзя сказать, устарели ли координаты. Пусто = геокодер ещё не звали.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="geocode_status",
            field=models.CharField(
                choices=[
                    ("not_attempted", "Геокодер не вызывался"),
                    ("ok", "Успех — однозначный результат провайдера"),
                    ("ambiguous", "Неоднозначно — ждёт подтверждения человеком"),
                    ("confirmed", "Подтверждено человеком"),
                    ("pending", "Сервис недоступен — повтор запланирован"),
                    ("failed", "Отказ провайдера — адрес не найден"),
                ],
                default="not_attempted",
                help_text="Исход геокодирования (§139). Только ``ok`` и ``confirmed`` делают строку геокодированной; ``pending`` — полноправный исход «сервис недоступен», а не отсутствие данных, и в расчёте расстояния не участвует.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="geocoded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда геокодер в последний раз отвечал по этому адресу (§139 «время геокодирования»). NULL = не отвечал ни разу. Заполняется при ЛЮБОМ исходе, включая pending и failed: иначе повторный прогон не отличит «не звали» от «звали час назад и сервис лежал».",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Широта места оказания услуги. NULL = неизвестна. Никаких умолчаний-чисел: 0.0 здесь — значение, а не «пусто».",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90")),
                    django.core.validators.MaxValueValidator(Decimal("90")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Долгота места оказания услуги. NULL = неизвестна. Никаких умолчаний-чисел: 0.0 здесь — значение, а не «пусто».",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180")),
                    django.core.validators.MaxValueValidator(Decimal("180")),
                ],
            ),
        ),
    ]
