# Generated by Django 5.2.5 on 2026-09-11 13:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_geocode_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Как место называют люди: «Салон на Пушкина», «Кабинет 3». Пусто — берётся адрес.",
                        max_length=120,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Адрес места, как его назвали. Вход геокодера.",
                        max_length=500,
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "geocode_source_address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Адрес в том виде, в каком его отдали геокодеру. Пусто = геокодер ещё не звали.",
                        max_length=500,
                    ),
                ),
                (
                    "geocode_normalized_address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Адрес, каким его вернул провайдер. Пусто = провайдер ничего не вернул.",
                        max_length=500,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="NULL = неизвестна. 0.0 здесь — значение, а не «пусто».",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="NULL = неизвестна. 0.0 здесь — значение, а не «пусто».",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "geocode_provider",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "geocode_precision",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("not_attempted", "Геокодер не вызывался"),
                            ("ok", "Успех — однозначный результат провайдера"),
                            (
                                "ambiguous",
                                "Неоднозначно — ждёт подтверждения человеком",
                            ),
                            ("confirmed", "Подтверждено человеком"),
                            ("pending", "Сервис недоступен — повтор запланирован"),
                            ("failed", "Отказ провайдера — адрес не найден"),
                        ],
                        default="not_attempted",
                        max_length=16,
                    ),
                ),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждено"),
                            ("review_required", "Требует проверки"),
                            ("inactive", "Недействительно"),
                        ],
                        default="review_required",
                        help_text="confirmed — здесь оказывают услуги, подтверждено человеком; review_required — происхождение неизвестно; inactive — тестовый, личный, недействительный.",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Основание: ссылка на решение, переписку, документ. Обязательно при confirmed.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто подтвердил место. Обязателен при confirmed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Салон, которому принадлежит место. NULL — самостоятельный мастер вне салона.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место оказания услуг",
                "verbose_name_plural": "Места оказания услуг",
                "ordering": ["tenant__name", "label", "address"],
                "indexes": [
                    models.Index(
                        fields=["status", "geocode_status"],
                        name="tenants_ser_status_1e3990_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "confirmed"), _negated=True),
                            models.Q(
                                ("confirmed_at__isnull", False),
                                ("confirmed_by__isnull", False),
                                models.Q(("confirmed_source_ref", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="servicelocation_confirmed_requires_provenance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("latitude__isnull", True), ("longitude__isnull", True)
                            ),
                            models.Q(
                                ("latitude__isnull", False),
                                ("longitude__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="servicelocation_coordinates_are_a_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude", 0), ("longitude", 0), _negated=True
                        ),
                        name="servicelocation_no_zero_zero",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("geocode_normalized_address", ""), _negated=True
                        ),
                        fields=("tenant", "geocode_normalized_address"),
                        name="servicelocation_point_is_unique",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
    ]
