# Generated by Django 5.2.5 on 2026-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_service_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="kind",
            field=models.CharField(
                choices=[("salon", "Салон"), ("solo", "Соло-мастер")],
                db_index=True,
                default="salon",
                help_text="salon — салон; solo — рабочее пространство соло-мастера (тот же UUID, что у тенанта бота).",
                max_length=8,
            ),
        ),
    ]
