# Generated by Django 5.2.5 on 2026-09-15 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_drf1828_tenant_kind"),
        ("users", "0022_drf1796_specialistpublicationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelocation",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private_studio", "Свой кабинет"),
                    ("salon_or_studio", "Салон или студия"),
                ],
                default="",
                help_text="Формат места соло-мастера: свой кабинет или салон/студия. Пусто — не указан.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="servicelocation",
            name="note_for_client",
            field=models.CharField(
                blank=True,
                default="",
                help_text="«Как клиенту вас найти?» — текст мастера, до 200 символов. Стирается при удалении аккаунта.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("mobile", "Выезд к клиентам")], max_length=16
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Город зоны — город workspace мастера (Tenant.city), не ввод.",
                        max_length=100,
                    ),
                ),
                (
                    "coverage",
                    models.CharField(
                        choices=[
                            ("whole_city", "По всему городу"),
                            ("later", "Настрою позже"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="users.specialistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона выезда мастера",
                "verbose_name_plural": "Зоны выезда мастеров",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("specialist", "kind"), name="servicearea_one_per_kind"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coverage__in", ["whole_city", "later"])),
                        name="servicearea_coverage_is_named",
                    ),
                ],
            },
        ),
    ]
