# Generated by Django 5.2.5 on 2026-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_drf1803_place_kind_note_service_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Демонстрационный салон: заведён для показа и отработки интерфейса. Остаётся живым и бронируемым, но обычному клиенту не показывается — видит только личность с `User.is_test_persona`. Читать этот флаг напрямую нельзя: видимость выражает один предикат `users.sellable`.",
            ),
        ),
    ]
