# Generated by Django 5.2.5 on 2026-09-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_drf2420_demo_and_test_persona"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelocation",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто подтвердил место. Обязателен при confirmed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
