# Generated by Django 5.2.5 on 2026-10-06 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0046_body_care_7a0_legal_class"),
        ("tenants", "0010_drf2612_provenance_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_ref",
                    models.CharField(
                        help_text="Номер лицензии, как в документе.", max_length=100
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Основание проверки: где документ, что именно сверено.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "covered_templates",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Каноны, которые лицензия покрывает. Нет в списке — не покрыт.",
                        related_name="medical_licenses",
                        to="services.servicetemplate",
                    ),
                ),
                (
                    "licensed_locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Места этого салона, указанные в лицензии.",
                        related_name="medical_licenses",
                        to="tenants.servicelocation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_licenses",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто проверил лицензию. Пусто — не проверена.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская лицензия",
                "verbose_name_plural": "Медицинские лицензии",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "license_ref"),
                        name="medicallicense_unique_ref_per_tenant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("license_ref", ""), _negated=True),
                        name="medicallicense_ref_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("verified_by__isnull", True),
                                ("verified_at__isnull", True),
                                ("verification_source_ref", ""),
                            ),
                            models.Q(
                                ("verified_by__isnull", False),
                                ("verified_at__isnull", False),
                                models.Q(
                                    ("verification_source_ref", ""), _negated=True
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="medicallicense_verification_all_or_nothing",
                    ),
                ],
            },
        ),
    ]
