# Generated by Django 5.2.5 on 2026-08-25 03:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesiredOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target",
                    models.SlugField(
                        help_text="Ключ объекта результата (напр. body_weight, edema)",
                        max_length=64,
                    ),
                ),
                (
                    "statement_text",
                    models.TextField(
                        help_text="Дословная формулировка пользователя; не нормализуется"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reduce", "Снизить"),
                            ("increase", "Увеличить"),
                            ("maintain", "Поддерживать"),
                        ],
                        help_text="Направление изменения; NULL при заданном desired_state_numeric",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "desired_state_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Желаемое числовое состояние; NULL при заданном direction",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыт"),
                            ("closed_by_user", "Закрыт пользователем"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desired_outcomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceRegistryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome_target",
                    models.SlugField(
                        help_text="Ключ объекта результата (DesiredOutcome.target)",
                        max_length=64,
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[("weight", "Вес"), ("self_assessment", "Самооценка")],
                        max_length=32,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("user_stated", "Указано пользователем")],
                        max_length=16,
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Код шкалы; пустая строка для типов без инструмента (weight)",
                        max_length=64,
                    ),
                ),
                ("approved_by", models.CharField(max_length=255)),
                ("approved_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["outcome_target"],
                "unique_together": {
                    ("outcome_target", "observation_type", "origin", "instrument")
                },
            },
        ),
        migrations.CreateModel(
            name="PersonalPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("closed_by_user", "Закрыт пользователем"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanOutcomeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="Срок цели; NULL = цель без срока",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("closed_by_user", "Закрыта пользователем"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_links",
                        to="wellness.desiredoutcome",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome_links",
                        to="wellness.personalplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[("weight", "Вес"), ("self_assessment", "Самооценка")],
                        max_length=32,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("user_stated", "Указано пользователем")],
                        default="user_stated",
                        max_length=16,
                    ),
                ),
                (
                    "instrument",
                    models.SlugField(
                        blank=True,
                        help_text="Версионированный код шкалы; обязателен для self_assessment, NULL для weight",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Числовое значение (weight, unit=kg фиксирована)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "value_ordinal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Порядковое значение 0–3 (self_assessment)",
                        null=True,
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Append-only исправление (§8): указывает на заменившую строку",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="wellness.progressobservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="desiredoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("direction__isnull", False),
                    ("desired_state_numeric__isnull", False),
                    _connector="OR",
                ),
                name="desiredoutcome_direction_or_numeric_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="personalplan_one_active_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="planoutcomelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("outcome",),
                name="planoutcomelink_one_active_per_outcome",
            ),
        ),
        migrations.AddIndex(
            model_name="progressobservation",
            index=models.Index(
                fields=["user", "observation_type", "observed_at"],
                name="progressobs_user_type_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="progressobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("instrument__isnull", True),
                        ("observation_type", "weight"),
                        ("value_numeric__isnull", False),
                        ("value_ordinal__isnull", True),
                    ),
                    models.Q(
                        ("instrument__isnull", False),
                        ("observation_type", "self_assessment"),
                        ("value_numeric__isnull", True),
                        ("value_ordinal__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="progressobservation_value_matches_type",
            ),
        ),
    ]
