# Generated by Django 5.2.5 on 2026-08-25 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellness", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("log_food", "Запись питания"),
                            ("log_water", "Запись воды"),
                        ],
                        help_text="Курируемый ключ обязательства; расширение — owner approval",
                        max_length=32,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("per_day", "Раз в день"),
                            ("per_week", "Раз в неделю"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Сколько раз за ведро каденса (день для per_day, неделя для per_week)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="wellness.personalplan",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["plan"], name="planaction_plan_idx")],
            },
        ),
    ]
