# Generated by Django 5.2.5 on 2026-09-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0007_anketaanswer_option_keys"),
        ("wellness", "0002_planaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalplan",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="goals.clientgoal",
            ),
        ),
        migrations.AddField(
            model_name="personalplan",
            name="goal_key",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Снимок ClientGoal.goal_key на момент составления плана (Plan Lite)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="planaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("log_food", "Запись питания"),
                    ("log_water", "Запись воды"),
                    ("book_service", "Запись на услугу"),
                ],
                help_text="Курируемый ключ обязательства; расширение — owner approval",
                max_length=32,
            ),
        ),
    ]
