# Generated by Django 5.2.5 on 2026-10-07 09:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0009_goal_text_origin"),
        ("wellness", "0007_seed_plan_templates_if_empty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("closed_by_user", "Закрыт пользователем"),
                    ("superseded", "Замещён сохранённым планом"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Действует"),
                            ("paused", "Приостановлен"),
                            ("superseded", "Замещён другим планом той же цели"),
                            ("archived", "В архиве"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "created_via",
                    models.CharField(
                        choices=[("confirmation", "Подтверждение человека")],
                        default="confirmation",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="sha256(subject, decision_id, подтверждение) — §4.9; считает сервер",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Цель плана; NULL — только после снятия цели (история), не при создании",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engine_plans",
                        to="goals.clientgoal",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engine_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "revision_no",
                    models.PositiveIntegerField(
                        help_text="Монотонный в рамках плана, с 1"
                    ),
                ),
                (
                    "steps_snapshot",
                    models.JSONField(
                        help_text="PlanStep целиком (§4.2) — снимок, не ссылки"
                    ),
                ),
                (
                    "assertions_snapshot",
                    models.JSONField(
                        default=list,
                        help_text="PlanningAssertion целиком — воспроизводимость (§4.4)",
                    ),
                ),
                (
                    "validation",
                    models.JSONField(help_text="PlanValidation на момент сборки (§6)"),
                ),
                (
                    "staleness",
                    models.CharField(
                        choices=[
                            ("none", "Актуальна"),
                            ("stale_rules", "Правила обновились"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "policy_versions",
                    models.JSONField(help_text="Шесть версий политик (§4.1)"),
                ),
                (
                    "created_from",
                    models.JSONField(help_text="{decision_id} | {recompute_event}"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="sha256 канонического JSON снимков — сверка повтора команды",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="wellness.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "revision_no"],
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                help_text="Текущая ревизия; NULL только внутри транзакции создания",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="wellness.planrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="planrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "revision_no"),
                name="planrevision_plan_revision_no_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["subject_user", "status"], name="plan_subject_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("goal",),
                name="plan_one_active_per_goal",
            ),
        ),
    ]
