# Generated by Django 5.2.5 on 2026-10-07 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_master_acknowledgement_drf2785"),
        ("services", "0046_body_care_7a0_legal_class"),
        ("wellness", "0008_plan_engine_durable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanStepBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_id", models.CharField(max_length=128)),
                (
                    "resolver_decision_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("recommendation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_step_booking",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_bookings",
                        to="wellness.plan",
                    ),
                ),
                (
                    "plan_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_bookings",
                        to="wellness.planrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "step_id", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["plan", "step_id"], name="planstepbooking_plan_step_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanStepResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_id",
                    models.CharField(
                        help_text="step_id шага в снимке этой ревизии", max_length=128
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("SERVICE", "SERVICE"), ("OFFER", "OFFER")],
                        max_length=16,
                    ),
                ),
                (
                    "resolver_decision_id",
                    models.CharField(
                        help_text="decision_id ответа резолвера, которым разрешён шаг",
                        max_length=64,
                    ),
                ),
                (
                    "recommendation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Только при реальной сохранённой Recommendation; до открытия C1 — NULL",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="services.servicetemplate",
                    ),
                ),
                (
                    "plan_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_resolutions",
                        to="wellness.planrevision",
                    ),
                ),
                (
                    "tenant_offer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Предложение салона; NULL на уровне SERVICE",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="services.salonservice",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_revision", "step_id", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan_revision", "step_id", "level"),
                        name="planstepresolution_one_per_level",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("level", "SERVICE"), ("tenant_offer__isnull", True)
                            ),
                            models.Q(
                                ("level", "OFFER"), ("tenant_offer__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="planstepresolution_offer_matches_level",
                    ),
                ],
            },
        ),
    ]
