# Generated by Django 5.2.5 on 2026-10-08 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellness", "0010_plan_step_safety_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("PLAN", "Весь план"), ("STEP", "Один шаг")],
                        max_length=8,
                    ),
                ),
                ("step_id", models.CharField(blank=True, default="", max_length=128)),
                ("cause", models.CharField(max_length=64)),
                ("question_id", models.CharField(max_length=128)),
                ("safety_state", models.CharField(max_length=16)),
                ("safety_policy_version", models.CharField(max_length=64)),
                ("safety_evaluated_at_revision", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="wellness.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanRestrictionLift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lift_kind", models.CharField(max_length=32)),
                (
                    "answer_option_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("safety_state", models.CharField(max_length=16)),
                ("safety_policy_version", models.CharField(max_length=64)),
                ("safety_evaluated_at_revision", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restriction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lift",
                        to="wellness.planrestriction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="planrestriction",
            index=models.Index(
                fields=["plan", "scope", "step_id"],
                name="planrestriction_plan_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="planrestriction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "PLAN"), ("step_id", "")),
                    models.Q(
                        ("scope", "STEP"), models.Q(("step_id", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="planrestriction_step_id_matches_scope",
            ),
        ),
    ]
