# Generated by Django 5.2.5 on 2026-10-08 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0009_goal_text_origin"),
        ("wellness", "0011_plan_restrictions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Действует"),
                    ("paused", "Приостановлен"),
                    ("proposed", "Предложение — ждёт подтверждения замены"),
                    ("superseded", "Замещён другим планом той же цели"),
                    ("archived", "В архиве"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "proposed")),
                fields=("goal",),
                name="plan_one_proposed_per_goal",
            ),
        ),
    ]
