# Generated by Django 6.0.3 on 2026-03-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='buffer_after_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Required gap (minutes) after this service before next booking'),
        ),
    ]
