# Generated by Django 6.0.3 on 2026-03-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_enhancements'),
        ('users', '0013_add_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.specialistprofile'),
        ),
    ]
