# Generated by Django 6.0.3 on 2026-04-20 10:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_updated_at_alter_service_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_short', models.CharField(help_text='Короткое имя для чипов/списков', max_length=40)),
                ('duration_default', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('duration_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('duration_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('is_popular', models.BooleanField(default=False, help_text='Показывать в верхней части списка категории')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='services.servicecategory')),
            ],
            options={
                'ordering': ['-is_popular', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_popular', 'sort_order'], name='services_se_categor_1feb5f_idx')],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
