# Generated by Django 6.0.3 on 2026-04-20 20:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_key', models.CharField(help_text='Нормализованный ключ региона: «penza», «moscow», «default»', max_length=50)),
                ('region_name', models.CharField(help_text='Человекочитаемое имя: «Пенза», «Москва»', max_length=100)),
                ('price_min', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_max', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_prices', to='services.servicetemplate')),
            ],
            options={
                'ordering': ['template', 'region_key'],
                'indexes': [models.Index(fields=['region_key'], name='services_re_region__9a1078_idx')],
                'unique_together': {('template', 'region_key')},
            },
        ),
    ]
