# Generated by Django 5.2.5 on 2026-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_regionalpricing'),
        ('users', '0004_specialistportfolio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['specialist', 'category', 'is_active'], name='svc_spec_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['specialist', 'price'], name='svc_spec_price_idx'),
        ),
    ]
