# Generated by Django 5.2.5 on 2026-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_tenant_servicecategory_tenant'),
        ('tenants', '0002_rename_tenants_ten_is_acti_2c1ec7_idx_tenants_ten_is_acti_c80453_idx'),
        ('users', '0009_personal_context_drf230'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'is_active'], name='svc_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['tenant', 'is_active'], name='svccat_tenant_active_idx'),
        ),
    ]
