# Generated by Django 5.2.5 on 2026-07-01 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_aftercare_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='contraindications',
            field=models.TextField(blank=True, default='', help_text='Противопоказания / оговорки (мед. профиль, разрешение врача и т.п.)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='requires_health_check',
            field=models.BooleanField(default=False, help_text='Услуга требует проверки противопоказаний перед записью'),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='duration_default',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='duration_max',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
    ]
