# Generated by Django 5.2.5 on 2026-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_external_busy_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="aftercare_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Approved post-visit aftercare advice. Sent verbatim via B9 T+2h push. Empty (default) suppresses the push.",
            ),
        ),
    ]
