# Generated by Django 5.2.5 on 2026-08-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_alter_service_aftercare_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Стабильный ключ подсказки; уходит в ClientGoal.goal_key и события воронки",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Человекочитаемая подпись чипа (рус.)", max_length=100
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "key"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="goaloption_active_sort_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GoalOptionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_option_links",
                        to="services.servicecategory",
                    ),
                ),
                (
                    "goal_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_links",
                        to="services.goaloption",
                    ),
                ),
            ],
            options={
                "ordering": ["goal_option", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["goal_option", "sort_order"],
                        name="goaloptcat_option_sort_idx",
                    )
                ],
                "unique_together": {("goal_option", "category")},
            },
        ),
    ]
