# Generated by Django 5.2.5 on 2026-09-08 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_goaloption_goaloptioncategory"),
        ("tenants", "0003_seed_default_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salonservice",
            name="mapping_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="mapping_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="mapping_confirmed_rule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="mapping_rule_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="mapping_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    ("unmapped", "Unmapped"),
                    ("review_required", "Review required"),
                    ("verified", "Verified"),
                ],
                default="unmapped",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="salonservice",
            index=models.Index(
                fields=["tenant", "mapping_status"],
                name="salonsvc_tenant_mapstatus_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mapping_status", "verified"), _negated=True),
                    models.Q(
                        ("mapping_confirmed_at__isnull", False),
                        models.Q(("mapping_source_ref", ""), _negated=True),
                        models.Q(
                            ("mapping_confirmed_by__isnull", False),
                            models.Q(("mapping_confirmed_rule", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="salonservice_verified_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mapping_confirmed_rule", ""),
                    models.Q(("mapping_rule_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="salonservice_rule_confirmation_carries_version",
            ),
        ),
    ]
