# Generated by Django 5.2.5 on 2026-09-10 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_mapping_status_not_recommendable"),
        ("tenants", "0004_tenant_address_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTemplateSynonym",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "normalized",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                (
                    "confirmed_rule",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "rule_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("confirmed_at", models.DateTimeField()),
                ("source_ref", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="services.servicetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "text"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "normalized"),
                        name="templatesynonym_template_normalized_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("source_ref", ""), _negated=True),
                            models.Q(
                                ("confirmed_by__isnull", False),
                                models.Q(("confirmed_rule", ""), _negated=True),
                                _connector="OR",
                            ),
                        ),
                        name="templatesynonym_requires_provenance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confirmed_by__isnull", False),
                            models.Q(("confirmed_rule", ""), _negated=True),
                            _negated=True,
                        ),
                        name="templatesynonym_provenance_is_who_xor_rule",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confirmed_rule", ""),
                            models.Q(("rule_version", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="templatesynonym_rule_carries_version",
                    ),
                ],
            },
        ),
    ]
