"""Жизненный цикл канонической услуги и дедовщина существующих строк.

**Что добавляется.** `ServiceTemplate.lifecycle` — `provisional` или
`approved` (§93), плюс провенанс одобрения той же формы, что у связи:
кто ИЛИ правило, версия у правила, дата, основание. Три
`CheckConstraint`, потому что одобрение — решение, а решение без автора
через месяц читается как умолчание.

**Умолчание поля — `provisional`.** Канон, заведённый кодом, миграцией
или чужой рукой, никем не проверен по определению.

**Что делает засыпка и чего она НЕ утверждает.** Строки, существующие
на момент этой миграции, получают `approved` правилом
`grandfathered_before_lifecycle`. Имя правила выбрано буквальным
намеренно: оно утверждает ровно то, что истинно по построению —
«строка существовала до появления жизненного цикла», — и **не**
утверждает, что кто-то её проверил.

Соблазн был назвать правило `owner_reference_catalog`. Это было бы
сильнее и неправдой: рабочий код создаёт шаблоны двумя командами
(`seed_canonical_catalog` — эталонный список владельца,
`seed_service_templates` — старый набор DRF-196), и на произвольной
базе засыпка накроет обе. На пилоте они совпадают с эталоном — замер
главного окна 10.09 на `dev-web-1` дал `ServiceTemplate = 1223`, ровно
столько строк в `services/seeds/canonical_catalog_2026-07.json`, — но
это свойство пилота, а не миграции.

Альтернативу «оставить всё черновым» отвергаю с причиной: тысяча с
лишним строк руками не одобряется, а на подбор `lifecycle` сегодня не
влияет (см. открытый вопрос ниже), значит дедовщина ничего не
разрешает и не запрещает — она лишь честно называет исходное
состояние. Обратная миграция возвращает эти строки в `provisional`.

**Открытый вопрос, который здесь НЕ решается.** Сегодня связь со
статусом `VERIFIED` на черновом каноне попадает в подбор: гейт §76
спрашивает только статус связи. Правильно ли это — вопрос владельцу, и
он упирается в два других его же незакрытых вопроса («кто оператор» и
«что значит после проверки»). Пока ответа нет, гейт не трогаем: второй
гейт, заведённый по чужой догадке, тише и опаснее его отсутствия.
Чтобы дыра не была молчаливой, рядом едет команда
`check_canon_invariants`, которая её считает.
"""
# Generated by Django 5.2.5 on 2026-09-10 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


#: Имя правила буквальное намеренно. Оно утверждает ровно то, что истинно
#: по построению — «строка существовала до появления жизненного цикла», —
#: и НЕ утверждает, что кто-то её проверил.
#:
#: Отвергнутый вариант: `owner_reference_catalog`. Он сильнее и неправда.
#: Шаблоны создают ДВЕ команды — `seed_canonical_catalog` (эталонный
#: список владельца) и `seed_service_templates` (старый набор DRF-196), —
#: и на произвольной базе засыпка накрывает обе. На пилоте они совпали:
#: замер главного окна 10.09 на `dev-web-1` дал `ServiceTemplate = 1223`,
#: ровно столько строк в `services/seeds/canonical_catalog_2026-07.json`.
#: **Это свойство пилота, а не системы**, и через полгода читать его как
#: свойство системы будет нельзя — на другой базе числа разойдутся.
#:
#: Имя сторожится тестом `test_grandfathering_rule_does_not_claim_a_human
#: _checked`: усилить формулировку при следующей правке ничего не стоит,
#: а проверить потом будет нечем.
GRANDFATHER_RULE = "grandfathered_before_lifecycle"
GRANDFATHER_VERSION = "0021"
GRANDFATHER_REF = (
    "строка существовала до миграции 0021; проверку человеком это НЕ означает"
)


def grandfather_existing(apps, schema_editor):
    """Существовавшие строки объявляются одобренными правилом.

    Пишется `update()` одним запросом: строк тысячи, и `save()` по
    одной здесь ничего не добавил бы — `clean()` у шаблона проверяет
    длительности, а не одобрение.
    """
    from django.utils import timezone

    ServiceTemplate = apps.get_model("services", "ServiceTemplate")
    now = timezone.now()
    touched = ServiceTemplate.objects.filter(lifecycle="provisional").update(
        lifecycle="approved",
        approved_by=None,
        approved_rule=GRANDFATHER_RULE,
        approval_rule_version=GRANDFATHER_VERSION,
        approved_at=now,
        approval_source_ref=GRANDFATHER_REF,
    )
    print(f"  grandfathered templates: {touched}")


def ungrandfather(apps, schema_editor):
    """Обратно — только те, кого одобрила именно эта миграция.

    По имени правила, а не по всем `approved`: откат не вправе снимать
    одобрение, поставленное человеком или сидом после накатки.
    """
    ServiceTemplate = apps.get_model("services", "ServiceTemplate")
    ServiceTemplate.objects.filter(approved_rule=GRANDFATHER_RULE).update(
        lifecycle="provisional",
        approved_rule="",
        approval_rule_version="",
        approved_at=None,
        approval_source_ref="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_template_synonyms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetemplate",
            name="approval_rule_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="approval_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="approved_rule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="lifecycle",
            field=models.CharField(
                choices=[("provisional", "Черновой"), ("approved", "Одобрен")],
                default="provisional",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="servicetemplate",
            index=models.Index(fields=["lifecycle"], name="svctpl_lifecycle_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lifecycle", "approved"), _negated=True),
                    models.Q(
                        ("approved_at__isnull", False),
                        models.Q(("approval_source_ref", ""), _negated=True),
                        models.Q(
                            ("approved_by__isnull", False),
                            models.Q(("approved_rule", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_approved_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", False),
                    models.Q(("approved_rule", ""), _negated=True),
                    _negated=True,
                ),
                name="servicetemplate_approval_is_who_xor_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_rule", ""),
                    models.Q(("approval_rule_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="servicetemplate_approval_rule_carries_version",
            ),
        ),
        migrations.RunPython(grandfather_existing, ungrandfather),
    ]

