# Generated by Django 5.2.5 on 2026-09-14 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0022_salonservice_verified_requires_template"),
        ("tenants", "0006_service_location"),
        ("users", "0020_specialistprofile_works_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonGapRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("duration_minutes", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На проверке"),
                            ("approved", "Подтверждена"),
                            ("needs_clarification", "Нужно уточнение"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("clarification_question", models.TextField(blank=True, default="")),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canon_gap_requests",
                        to="services.servicetemplate",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canon_gap_requests",
                        to="users.specialistprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canon_gap_requests",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка о разрыве канона",
                "verbose_name_plural": "Заявки о разрыве канона",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["specialist", "status"],
                        name="canongap_specialist_status_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="canongap_status_created_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "approved"), _negated=True),
                            ("resolved_template__isnull", False),
                            _connector="OR",
                        ),
                        name="canongap_approved_requires_template",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "pending"), _negated=True),
                            ("resolved_template__isnull", True),
                            _connector="OR",
                        ),
                        name="canongap_pending_binds_no_template",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "pending"),
                            models.Q(
                                ("decided_by__isnull", False),
                                ("decided_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="canongap_decision_requires_actor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "needs_clarification"), _negated=True),
                            models.Q(("clarification_question", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="canongap_clarification_requires_question",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "rejected"), _negated=True),
                            models.Q(("rejection_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="canongap_rejection_requires_reason",
                    ),
                ],
            },
        ),
    ]
