# Generated by Django 5.2.5 on 2026-09-12 10:19

import services.canonical_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0022_salonservice_verified_requires_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetemplate",
            name="canonical_code",
            field=models.CharField(
                blank=True,
                help_text="Код эталонного справочника (N.N.N). Пусто — канон не из эталонного списка. После установки не меняется.",
                max_length=16,
                null=True,
                validators=[services.canonical_code.validate_canonical_code],
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("canonical_code__isnull", False)),
                fields=("canonical_code",),
                name="servicetemplate_canonical_code_uniq",
            ),
        ),
    ]
