# Generated by Django 5.2.5 on 2026-09-20 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_canongaprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalDirection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area_key",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Ключ ответа шага «area» анкеты (face/body/hair/hands/overall); пусто — запасное направление под цель целиком",
                        max_length=64,
                    ),
                ),
                (
                    "what",
                    models.CharField(
                        help_text="Направление одной фразой (макет C04.1: «Уменьшить утреннюю отёчность…»)",
                        max_length=200,
                    ),
                ),
                (
                    "subline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Подстрока под направлением (макет: «Сфокусируемся на этом — …»)",
                        max_length=300,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directions",
                        to="services.goaloption",
                    ),
                ),
            ],
            options={
                "ordering": ["goal_option", "sort_order", "area_key"],
                "unique_together": {("goal_option", "area_key")},
            },
        ),
    ]
