# Generated by Django 5.2.5 on 2026-09-29 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_master_select_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureCapability",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("system_inference", "System inference"),
                            ("approved", "Approved"),
                        ],
                        default="system_inference",
                        max_length=24,
                    ),
                ),
                (
                    "claim_scope",
                    models.CharField(
                        choices=[
                            ("supported", "Supported"),
                            ("not_supported", "Not supported"),
                            ("prohibited_claim", "Prohibited claim"),
                        ],
                        default="not_supported",
                        max_length=24,
                    ),
                ),
                ("limitations", models.TextField(blank=True, default="")),
                (
                    "evidence_source",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "evidence_kind",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "confirmed_rule",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "rule_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("text_client", models.TextField(blank=True, default="")),
                ("text_professional", models.TextField(blank=True, default="")),
                ("expected_effect", models.TextField(blank=True, default="")),
                (
                    "result_timeframe",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capabilities",
                        to="services.servicetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CapabilityGoalLink",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("system_inference", "System inference"),
                            ("approved", "Approved"),
                        ],
                        default="system_inference",
                        max_length=24,
                    ),
                ),
                (
                    "claim_scope",
                    models.CharField(
                        choices=[
                            ("supported", "Supported"),
                            ("not_supported", "Not supported"),
                            ("prohibited_claim", "Prohibited claim"),
                        ],
                        default="not_supported",
                        max_length=24,
                    ),
                ),
                ("limitations", models.TextField(blank=True, default="")),
                (
                    "evidence_source",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "evidence_kind",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "confirmed_rule",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "rule_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_pattern", models.TextField(blank=True, default="")),
                (
                    "result_horizon",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("variability_note", models.TextField(blank=True, default="")),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_links",
                        to="services.goaloption",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_links",
                        to="services.procedurecapability",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="procedurecapability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(
                        ("confirmed_at__isnull", False),
                        models.Q(("source_ref", ""), _negated=True),
                        models.Q(
                            ("confirmed_by__isnull", False),
                            models.Q(("confirmed_rule", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="procedurecapability_approved_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecapability",
            constraint=models.UniqueConstraint(
                fields=("template", "key"), name="procedurecapability_template_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitygoallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(
                        ("confirmed_at__isnull", False),
                        models.Q(("source_ref", ""), _negated=True),
                        models.Q(
                            ("confirmed_by__isnull", False),
                            models.Q(("confirmed_rule", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="capabilitygoallink_approved_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitygoallink",
            constraint=models.UniqueConstraint(
                fields=("capability", "goal"),
                name="capabilitygoallink_capability_goal_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitygoallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("course_pattern", ""),
                    models.Q(
                        models.Q(("variability_note", ""), _negated=True),
                        models.Q(("evidence_source", ""), _negated=True),
                        models.Q(("source_ref", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="capabilitygoallink_course_requires_variability_and_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitygoallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("course_pattern__regex", "^\\s*[0-9]+([.,][0-9]+)?\\s*$"),
                    _negated=True,
                ),
                name="capabilitygoallink_course_not_a_bare_number",
            ),
        ),
    ]
