# Generated by Django 5.2.5 on 2026-09-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_procedure_capability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetemplate",
            name="health_check_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="health_check_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="health_check_confirmed_rule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="health_check_origin",
            field=models.CharField(
                choices=[("inferred", "Inferred"), ("confirmed", "Confirmed")],
                default="inferred",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="health_check_rule_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="health_check_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("health_check_origin", "confirmed"), _negated=True),
                    models.Q(
                        ("health_check_confirmed_at__isnull", False),
                        models.Q(("health_check_source_ref", ""), _negated=True),
                        models.Q(
                            ("health_check_confirmed_by__isnull", False),
                            models.Q(
                                ("health_check_confirmed_rule", ""), _negated=True
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_health_check_confirmed_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("health_check_confirmed_by__isnull", False),
                    models.Q(("health_check_confirmed_rule", ""), _negated=True),
                    _negated=True,
                ),
                name="servicetemplate_health_check_is_who_xor_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("health_check_confirmed_rule", ""),
                    models.Q(("health_check_rule_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="servicetemplate_health_check_rule_carries_version",
            ),
        ),
    ]
