# Generated by Django 5.2.5 on 2026-10-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0033_drf2726_prohibited_statement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capabilitygoallink",
            options={
                "permissions": [
                    (
                        "approve_capabilitygoallink",
                        "Может подтверждать связи возможностей с целями",
                    )
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="procedurecapability",
            options={
                "ordering": ["template", "key"],
                "permissions": [
                    (
                        "approve_procedurecapability",
                        "Может подтверждать возможности процедур",
                    )
                ],
            },
        ),
    ]
