# Generated by Django 5.2.5 on 2026-10-02 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0036_drf2742_evidence_kind_closed_list"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureContraindication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("condition", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("exclude", "Исключить (не проводить / исключить зону)"),
                            ("postpone", "Отложить"),
                            ("refer_to_doctor", "Направить к врачу"),
                            ("emergency", "Экстренная помощь"),
                        ],
                        max_length=16,
                    ),
                ),
                ("action_note", models.TextField(blank=True, default="")),
                ("scope_note", models.TextField(blank=True, default="")),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "evidence_source",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "evidence_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clinical_guideline", "Клиническая рекомендация"),
                            (
                                "systematic_review",
                                "Систематический обзор / мета-анализ",
                            ),
                            ("rct", "Рандомизированное контролируемое исследование"),
                            (
                                "manufacturer_ifu",
                                "Официальная инструкция производителя",
                            ),
                            ("regulatory_document", "Регуляторный документ"),
                            ("professional_consensus", "Профессиональный консенсус"),
                            ("legal_rule", "Правовая норма"),
                            ("product_policy", "Продуктовая политика"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("system_inference", "System inference"),
                            ("approved", "Approved"),
                        ],
                        default="system_inference",
                        max_length=24,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "templates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contraindication_rules",
                        to="services.servicetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "permissions": [
                    (
                        "review_procedurecontraindication",
                        "Может отмечать противопоказание проверенным (рецензент)",
                    ),
                    (
                        "approve_procedurecontraindication",
                        "Может подтверждать противопоказания",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("condition", ""), _negated=True),
                        name="procedurecontraindication_condition_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                ["exclude", "postpone", "refer_to_doctor", "emergency"],
                            )
                        ),
                        name="procedurecontraindication_action_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reviewed_by__isnull", True),
                                ("reviewed_at__isnull", True),
                            ),
                            models.Q(
                                ("reviewed_by__isnull", False),
                                ("reviewed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="procedurecontraindication_review_is_whole",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "approved"), _negated=True),
                            models.Q(
                                models.Q(("source_ref", ""), _negated=True),
                                (
                                    "evidence_kind__in",
                                    [
                                        "clinical_guideline",
                                        "systematic_review",
                                        "rct",
                                        "manufacturer_ifu",
                                        "regulatory_document",
                                        "professional_consensus",
                                        "legal_rule",
                                        "product_policy",
                                    ],
                                ),
                                ("review_date__isnull", False),
                                ("reviewed_by__isnull", False),
                                ("reviewed_at__isnull", False),
                                ("confirmed_by__isnull", False),
                                ("confirmed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="procedurecontraindication_approved_complete",
                    ),
                ],
            },
        ),
    ]
