# Generated by Django 5.2.5 on 2026-10-02 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0038_drf2726_reviewer_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureContraindication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("condition", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("exclude", "Исключить (не проводить / исключить зону)"),
                            ("postpone", "Отложить"),
                            ("refer_to_doctor", "Направить к врачу"),
                            ("emergency", "Экстренная помощь"),
                        ],
                        max_length=16,
                    ),
                ),
                ("action_note", models.TextField(blank=True, default="")),
                ("scope_note", models.TextField(blank=True, default="")),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "evidence_source",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "evidence_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clinical_guideline", "Клиническая рекомендация"),
                            (
                                "systematic_review",
                                "Систематический обзор / мета-анализ",
                            ),
                            ("rct", "Рандомизированное контролируемое исследование"),
                            (
                                "manufacturer_ifu",
                                "Официальная инструкция производителя",
                            ),
                            ("regulatory_document", "Регуляторный документ"),
                            ("professional_consensus", "Профессиональный консенсус"),
                            ("legal_rule", "Правовая норма"),
                            ("product_policy", "Продуктовая политика"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("system_inference", "System inference"),
                            ("approved", "Approved"),
                        ],
                        default="system_inference",
                        max_length=24,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
                "permissions": [
                    (
                        "approve_procedurecontraindication",
                        "Может подтверждать противопоказания",
                    )
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="claimapprovalreset",
            name="claimapprovalreset_at_most_one_claim",
        ),
        migrations.AlterField(
            model_name="claimapprovalreset",
            name="claim_kind",
            field=models.CharField(
                choices=[
                    ("capability", "Возможность"),
                    ("goal_link", "Связь с целью"),
                    ("contraindication", "Противопоказание"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="procedurecontraindication",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="procedurecontraindication",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedurecontraindication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedurecontraindication",
            name="templates",
            field=models.ManyToManyField(
                blank=True,
                related_name="contraindication_rules",
                to="services.servicetemplate",
            ),
        ),
        migrations.AddField(
            model_name="claimapprovalreset",
            name="contraindication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_resets",
                to="services.procedurecontraindication",
            ),
        ),
        migrations.AddConstraint(
            model_name="claimapprovalreset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("capability__isnull", True), ("goal_link__isnull", True)),
                    models.Q(
                        ("capability__isnull", True), ("contraindication__isnull", True)
                    ),
                    models.Q(
                        ("goal_link__isnull", True), ("contraindication__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="claimapprovalreset_at_most_one_claim",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecontraindication",
            constraint=models.CheckConstraint(
                condition=models.Q(("condition", ""), _negated=True),
                name="procedurecontraindication_condition_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecontraindication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        ["exclude", "postpone", "refer_to_doctor", "emergency"],
                    )
                ),
                name="procedurecontraindication_action_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecontraindication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reviewed_by__isnull", True), ("reviewed_at__isnull", True)
                    ),
                    models.Q(
                        ("reviewed_by__isnull", False), ("reviewed_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="procedurecontraindication_review_is_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecontraindication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(
                        models.Q(("source_ref", ""), _negated=True),
                        (
                            "evidence_kind__in",
                            [
                                "clinical_guideline",
                                "systematic_review",
                                "rct",
                                "manufacturer_ifu",
                                "regulatory_document",
                                "professional_consensus",
                                "legal_rule",
                                "product_policy",
                            ],
                        ),
                        ("review_date__isnull", False),
                        ("reviewed_by__isnull", False),
                        ("reviewed_at__isnull", False),
                        ("confirmed_by__isnull", False),
                        ("confirmed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="procedurecontraindication_approved_complete",
            ),
        ),
    ]
