# Generated by Django 5.2.5 on 2026-10-06 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0039_drf2741_contraindication_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetemplate",
            name="canonical_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="clinical_policy_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="legal_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="owner_policy_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="service_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("body_wrap", "Обёртывание"),
                    ("spa_body", "SPA-уход за телом"),
                    ("mechanical_scrub", "Механический скраб"),
                    ("acid_care", "Кислотный уход"),
                ],
                help_text="Семейство body-care; пусто — услуга вне body-care",
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_family__isnull", True),
                    models.Q(("canonical_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="servicetemplate_family_requires_canonical_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_family__isnull", True),
                    (
                        "service_family__in",
                        ["body_wrap", "spa_body", "mechanical_scrub", "acid_care"],
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_service_family_known",
            ),
        ),
    ]
