# Generated by Django 5.2.5 on 2026-10-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0041_body_care_cat1_service_family"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetemplate",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="retired_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="retired_rule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="retirement_rule_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="retirement_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="servicetemplate",
            name="lifecycle",
            field=models.CharField(
                choices=[
                    ("provisional", "Черновой"),
                    ("candidate", "Кандидат"),
                    ("approved", "Одобрен"),
                    ("retired", "Выведен"),
                ],
                default="provisional",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lifecycle", "retired"), _negated=True),
                    models.Q(
                        ("retired_at__isnull", False),
                        models.Q(("retirement_source_ref", ""), _negated=True),
                        models.Q(
                            ("retired_by__isnull", False),
                            models.Q(("retired_rule", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_retired_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retired_by__isnull", False),
                    models.Q(("retired_rule", ""), _negated=True),
                    _negated=True,
                ),
                name="servicetemplate_retirement_is_who_xor_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retired_rule", ""),
                    models.Q(("retirement_rule_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="servicetemplate_retirement_rule_carries_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "lifecycle__in",
                        ["provisional", "candidate", "approved", "retired"],
                    )
                ),
                name="servicetemplate_lifecycle_known",
            ),
        ),
    ]
