# Generated by Django 5.2.5 on 2026-10-06 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0042_body_care_cat2_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonservice",
            name="configuration_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.CreateModel(
            name="OfferingConfigFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("product_name", "Продукт"),
                            ("product_article", "Артикул"),
                            ("manufacturer", "Производитель"),
                            ("instruction_version", "Версия инструкции"),
                            ("instruction_region", "Регион инструкции"),
                            ("application_area", "Зона нанесения"),
                            ("application_area_size", "Размер зоны"),
                            ("mode", "Режим"),
                            ("exposure_seconds", "Время экспозиции, с"),
                            ("application_count", "Число нанесений"),
                            ("covering_type", "Тип укрытия"),
                            ("removal_method", "Способ снятия"),
                            ("aftercare", "Уход после"),
                            ("additional_modality", "Дополнительная модальность"),
                            ("heat_mode", "Тепловой режим"),
                            ("cold_mode", "Холодовой режим"),
                            ("compression_mode", "Компрессия"),
                            ("device_reference", "Аппарат"),
                            ("protocol_source", "Источник протокола"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("known", "Известно"),
                            ("unknown", "Неизвестно"),
                            ("not_applicable", "Не применимо"),
                            ("not_provided", "Не предоставлено"),
                            ("conflict", "Противоречие"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salon_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_facts",
                        to="services.salonservice",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("salon_service", "field"),
                        name="offeringconfigfact_one_fact_per_field",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "field__in",
                                [
                                    "product_name",
                                    "product_article",
                                    "manufacturer",
                                    "instruction_version",
                                    "instruction_region",
                                    "application_area",
                                    "application_area_size",
                                    "mode",
                                    "exposure_seconds",
                                    "application_count",
                                    "covering_type",
                                    "removal_method",
                                    "aftercare",
                                    "additional_modality",
                                    "heat_mode",
                                    "cold_mode",
                                    "compression_mode",
                                    "device_reference",
                                    "protocol_source",
                                ],
                            )
                        ),
                        name="offeringconfigfact_field_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "known",
                                    "unknown",
                                    "not_applicable",
                                    "not_provided",
                                    "conflict",
                                ],
                            )
                        ),
                        name="offeringconfigfact_state_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "known"), _negated=True),
                            models.Q(
                                ("value__isnull", False),
                                models.Q(("source_ref", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="offeringconfigfact_known_requires_value_and_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "state__in",
                                    ["unknown", "not_applicable", "not_provided"],
                                ),
                                _negated=True,
                            ),
                            ("value__isnull", True),
                            _connector="OR",
                        ),
                        name="offeringconfigfact_absent_states_carry_no_value",
                    ),
                ],
            },
        ),
    ]
