# Generated by Django 5.2.5 on 2026-10-06 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0043_body_care_cat3_config_facts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringconfigfact",
            name="capture_rule_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="offeringconfigfact",
            name="captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offeringconfigfact",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offeringconfigfact",
            name="captured_rule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="offeringconfigfact",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manufacturer_instruction", "Инструкция производителя"),
                    ("protocol_document", "Документ протокола"),
                    ("owner_input", "Ввод владельца"),
                    ("salon_input", "Ввод салона"),
                    ("physician_policy", "Политика врача"),
                    ("canonical_policy", "Каноническая политика"),
                    ("system_derived", "Выведено системой"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringconfigfact",
            name="source_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="offeringconfigfact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "known"), _negated=True),
                    ("source_type__isnull", False),
                    _connector="OR",
                ),
                name="offeringconfigfact_known_requires_source_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringconfigfact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_type__isnull", True),
                    (
                        "source_type__in",
                        [
                            "manufacturer_instruction",
                            "protocol_document",
                            "owner_input",
                            "salon_input",
                            "physician_policy",
                            "canonical_policy",
                            "system_derived",
                        ],
                    ),
                    _connector="OR",
                ),
                name="offeringconfigfact_source_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringconfigfact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("captured_by__isnull", False),
                    models.Q(("captured_rule", ""), _negated=True),
                    _negated=True,
                ),
                name="offeringconfigfact_capture_is_who_xor_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringconfigfact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("captured_rule", ""),
                    models.Q(("capture_rule_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="offeringconfigfact_capture_rule_carries_version",
            ),
        ),
    ]
