# Generated by Django 5.2.5 on 2026-10-06 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0044_body_care_cat4_fact_provenance"),
        ("tenants", "0010_drf2612_provenance_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salonservice",
            name="config_review_rule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="config_review_rule_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="config_review_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="config_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="config_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="config_reviewed_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="config_reviewed_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("config_reviewed_version", ""),
                    models.Q(
                        ("config_reviewed_at__isnull", False),
                        models.Q(("config_review_source_ref", ""), _negated=True),
                        models.Q(("config_reviewed_fingerprint", ""), _negated=True),
                        models.Q(
                            ("config_reviewed_by__isnull", False),
                            models.Q(("config_review_rule", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="salonservice_config_review_requires_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("config_reviewed_by__isnull", False),
                    models.Q(("config_review_rule", ""), _negated=True),
                    _negated=True,
                ),
                name="salonservice_config_review_is_who_xor_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("config_review_rule", ""),
                    models.Q(("config_review_rule_version", ""), _negated=True),
                    _connector="OR",
                ),
                name="salonservice_config_review_rule_carries_version",
            ),
        ),
    ]
