# Generated by Django 5.2.5 on 2026-10-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0045_body_care_cat6_config_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetemplate",
            name="legal_class_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="legal_class_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="legal_class_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="legal_service_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_medical_cosmetic", "Немедицинская косметическая"),
                    ("medical_cosmetology", "Медицинская косметология"),
                    ("medical_other", "Иная медицинская"),
                    ("legal_review_required", "Нужна юридическая проверка"),
                ],
                help_text="Юридический класс (§7A.1); пусто — не установлен, читается как «не разрешено»",
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="practitioner_class_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="practitioner_class_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="practitioner_class_source_ref",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="required_practitioner_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cosmetic_esthetician", "Косметик-эстетист"),
                    ("nurse_cosmetology", "Медсестра по косметологии"),
                    ("physician_cosmetologist", "Врач-косметолог"),
                    ("medical_specialist", "Врач-специалист"),
                    ("protocol_specific", "По протоколу"),
                ],
                help_text="Требуемая квалификация исполнителя (§7A.4); пусто — не установлена",
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legal_service_class__isnull", True),
                    (
                        "legal_service_class__in",
                        [
                            "non_medical_cosmetic",
                            "medical_cosmetology",
                            "medical_other",
                            "legal_review_required",
                        ],
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_legal_service_class_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_practitioner_class__isnull", True),
                    (
                        "required_practitioner_class__in",
                        [
                            "cosmetic_esthetician",
                            "nurse_cosmetology",
                            "physician_cosmetologist",
                            "medical_specialist",
                            "protocol_specific",
                        ],
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_practitioner_class_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legal_service_class__isnull", True),
                    models.Q(
                        ("legal_class_confirmed_by__isnull", False),
                        ("legal_class_confirmed_at__isnull", False),
                        models.Q(("legal_class_source_ref", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_legal_class_requires_confirmation",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_practitioner_class__isnull", True),
                    models.Q(
                        ("practitioner_class_confirmed_by__isnull", False),
                        ("practitioner_class_confirmed_at__isnull", False),
                        models.Q(("practitioner_class_source_ref", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_practitioner_class_requires_confirmation",
            ),
        ),
    ]
