# Generated by Django 5.2.5 on 2026-10-08 07:38

"""Пометка «синтетика» — поля, замки и триггеры (решение владельца 08.10.2026).

Строк миграция не создаёт и не правит: после неё синтетических строк в базе
ноль. Правило и его читатели — ``services.synthetic``.

CHECK умеет только одну строку. Два свойства он выразить не может, поэтому
они стоят триггерами:

* **неизменяемость** — пометка ставится при создании и не меняется никогда.
  Без этого «снял пометку → подтвердил» обходило бы замки «синтетика не
  approved / не verified». Триггер ловит и ``QuerySet.update()``;
* **согласованность между таблицами** — способность и её канон, услуга
  салона и её канон, связь с целью и её способность несут одну пометку.
  Иначе синтетическая способность на настоящем каноне под флагом сделала бы
  кандидатами настоящие предложения всех салонов.

Имена триггеров выбраны с расчётом: при одном событии Postgres исполняет их
по алфавиту, и ``…_synthetic_mark_is_immutable`` идёт раньше
``…_synthetic_stays_apart`` — попытка сменить пометку отвечает своей причиной,
а не следствием.

Ошибки триггеров идут с кодом ``23514`` (check_violation) — Django отдаёт их
как ``IntegrityError``, тем же родом, что нарушение CHECK.
"""

from django.conf import settings
from django.db import migrations, models


TRIGGERS = r"""
CREATE FUNCTION services_synthetic_mark_is_immutable() RETURNS trigger AS $$
BEGIN
    IF NEW.synthetic IS DISTINCT FROM OLD.synthetic THEN
        RAISE EXCEPTION 'synthetic_mark_is_immutable: % row % — the mark is set at creation and never changes',
            TG_TABLE_NAME, OLD.id USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER servicetemplate_synthetic_mark_is_immutable
    BEFORE UPDATE ON services_servicetemplate
    FOR EACH ROW EXECUTE FUNCTION services_synthetic_mark_is_immutable();
CREATE TRIGGER salonservice_synthetic_mark_is_immutable
    BEFORE UPDATE ON services_salonservice
    FOR EACH ROW EXECUTE FUNCTION services_synthetic_mark_is_immutable();
CREATE TRIGGER procedurecapability_synthetic_mark_is_immutable
    BEFORE UPDATE ON services_procedurecapability
    FOR EACH ROW EXECUTE FUNCTION services_synthetic_mark_is_immutable();
CREATE TRIGGER capabilitygoallink_synthetic_mark_is_immutable
    BEFORE UPDATE ON services_capabilitygoallink
    FOR EACH ROW EXECUTE FUNCTION services_synthetic_mark_is_immutable();

CREATE FUNCTION services_capability_binding_keeps_synthetic_apart() RETURNS trigger AS $$
BEGIN
    IF (SELECT synthetic FROM services_procedurecapability WHERE id = NEW.capability_id)
       IS DISTINCT FROM
       (SELECT synthetic FROM services_servicetemplate WHERE id = NEW.template_id) THEN
        RAISE EXCEPTION 'synthetic_binds_only_to_synthetic: capability % and template % carry different marks',
            NEW.capability_id, NEW.template_id USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER capabilitytemplate_synthetic_stays_apart
    BEFORE INSERT OR UPDATE ON services_capabilitytemplate
    FOR EACH ROW EXECUTE FUNCTION services_capability_binding_keeps_synthetic_apart();

CREATE FUNCTION services_salon_service_keeps_synthetic_apart() RETURNS trigger AS $$
BEGIN
    IF NEW.template_id IS NOT NULL
       AND (SELECT synthetic FROM services_servicetemplate WHERE id = NEW.template_id)
           IS DISTINCT FROM NEW.synthetic THEN
        RAISE EXCEPTION 'synthetic_binds_only_to_synthetic: salon service % and template % carry different marks',
            NEW.id, NEW.template_id USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER salonservice_synthetic_stays_apart
    BEFORE INSERT OR UPDATE ON services_salonservice
    FOR EACH ROW EXECUTE FUNCTION services_salon_service_keeps_synthetic_apart();

CREATE FUNCTION services_goal_link_keeps_synthetic_apart() RETURNS trigger AS $$
BEGIN
    IF (SELECT synthetic FROM services_procedurecapability WHERE id = NEW.capability_id)
       IS DISTINCT FROM NEW.synthetic THEN
        RAISE EXCEPTION 'synthetic_binds_only_to_synthetic: goal link % and capability % carry different marks',
            NEW.id, NEW.capability_id USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER capabilitygoallink_synthetic_stays_apart
    BEFORE INSERT OR UPDATE ON services_capabilitygoallink
    FOR EACH ROW EXECUTE FUNCTION services_goal_link_keeps_synthetic_apart();
"""

DROP_TRIGGERS = r"""
DROP TRIGGER capabilitygoallink_synthetic_stays_apart ON services_capabilitygoallink;
DROP TRIGGER salonservice_synthetic_stays_apart ON services_salonservice;
DROP TRIGGER capabilitytemplate_synthetic_stays_apart ON services_capabilitytemplate;
DROP TRIGGER capabilitygoallink_synthetic_mark_is_immutable ON services_capabilitygoallink;
DROP TRIGGER procedurecapability_synthetic_mark_is_immutable ON services_procedurecapability;
DROP TRIGGER salonservice_synthetic_mark_is_immutable ON services_salonservice;
DROP TRIGGER servicetemplate_synthetic_mark_is_immutable ON services_servicetemplate;
DROP FUNCTION services_goal_link_keeps_synthetic_apart();
DROP FUNCTION services_salon_service_keeps_synthetic_apart();
DROP FUNCTION services_capability_binding_keeps_synthetic_apart();
DROP FUNCTION services_synthetic_mark_is_immutable();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0051_salon_health_check_answer_origin"),
        ("tenants", "0011_body_care_7a2_medical_license"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitygoallink",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procedurecapability",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="capabilitygoallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False),
                    models.Q(("status", "approved"), _negated=True),
                    _connector="OR",
                ),
                name="capabilitygoallink_synthetic_is_never_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecapability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False),
                    models.Q(("status", "approved"), _negated=True),
                    _connector="OR",
                ),
                name="procedurecapability_synthetic_is_never_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False),
                    models.Q(("mapping_status", "verified"), _negated=True),
                    _connector="OR",
                ),
                name="salonservice_synthetic_is_never_verified",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False),
                    models.Q(
                        ("health_check_confirmed_by__isnull", True),
                        (
                            "health_check_confirmed_rule__in",
                            ["", "synthetic-test-data"],
                        ),
                    ),
                    _connector="OR",
                ),
                name="salonservice_synthetic_health_only_by_synthetic_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("health_check_confirmed_rule", "synthetic-test-data"),
                        _negated=True,
                    ),
                    ("synthetic", True),
                    _connector="OR",
                ),
                name="salonservice_synthetic_rule_only_on_synthetic",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False),
                    models.Q(
                        ("health_check_confirmed_by__isnull", True),
                        (
                            "health_check_confirmed_rule__in",
                            ["", "synthetic-test-data"],
                        ),
                    ),
                    _connector="OR",
                ),
                name="servicetemplate_synthetic_health_only_by_synthetic_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("health_check_confirmed_rule", "synthetic-test-data"),
                        _negated=True,
                    ),
                    ("synthetic", True),
                    _connector="OR",
                ),
                name="servicetemplate_synthetic_rule_only_on_synthetic",
            ),
        ),
        migrations.RunSQL(sql=TRIGGERS, reverse_sql=DROP_TRIGGERS),
    ]
