# Generated by Django 5.2.5 on 2026-10-08 19:03

"""Версия знания — отпечаток содержания и основания (DRF-2879).

Решение владельца: «Основание входит в версию знания. Значимое изменение
источника, его редакции или интерпретации требует повторного подтверждения и
перепроверки зависимых шагов. Сохранённый план не переписывать молча».

Отпечаток считает БАЗА — триггером при каждой записи строки, поэтому правка
через ``QuerySet.update()`` его тоже пересчитывает. Состав полей — тот же,
что в ``ClaimEvidence.FINGERPRINT_FIELDS`` и ``OWN_FINGERPRINT_FIELDS``
класса; узел ``test_knowledge_fingerprint_2879`` сверяет перечень в SQL с
перечнем в модели. Префикс ``v1:`` — версия СХЕМЫ отпечатка: смена состава
полей не должна выглядеть как правка знания.

``approved_fingerprint`` триггер ставит в момент подтверждения: переход в
``approved``, новое подтверждение (сменилась ``confirmed_at``) либо первое
появление отпечатка у уже подтверждённой строки. Последнее — заполнение
существующих строк: **всё подтверждённое до этой миграции принимается
неизменённым с момента подтверждения; проверить это нечем.**

Ограничение ``…_approved_content_matches_approval`` после заполнения делает
состояние «подтверждено, а содержание уже другое» невозможным. Обойти его
двумя записями нельзя: очистить ``approved_fingerprint`` у подтверждённой
строки ограничение не даст.
"""

from django.conf import settings
from django.db import migrations, models


FINGERPRINTS = r"""
CREATE FUNCTION services_capability_fingerprint() RETURNS trigger AS $$
BEGIN
    NEW.content_fingerprint := 'v1:' || encode(sha256(convert_to(concat_ws(chr(31),
        coalesce(NEW.claim_type, ''), coalesce(NEW.claim_scope, ''), coalesce(NEW.limitations, ''),
        coalesce(NEW.prohibited_statement, ''), coalesce(NEW.evidence_source, ''),
        coalesce(NEW.evidence_kind, ''), coalesce(NEW.source_ref, ''),
        coalesce(NEW.key, ''), coalesce(NEW.text_client, ''), coalesce(NEW.text_professional, ''),
        coalesce(NEW.expected_effect, ''), coalesce(NEW.result_timeframe, ''),
        coalesce(NEW.variability_note, '')
    ), 'UTF8')), 'hex');
    IF NEW.status = 'approved' THEN
        IF TG_OP = 'INSERT' OR OLD.status <> 'approved' OR OLD.approved_fingerprint = ''
           OR NEW.confirmed_at IS DISTINCT FROM OLD.confirmed_at THEN
            NEW.approved_fingerprint := NEW.content_fingerprint;
        END IF;
    ELSE
        NEW.approved_fingerprint := '';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER procedurecapability_fingerprint
    BEFORE INSERT OR UPDATE ON services_procedurecapability
    FOR EACH ROW EXECUTE FUNCTION services_capability_fingerprint();

CREATE FUNCTION services_goal_link_fingerprint() RETURNS trigger AS $$
BEGIN
    NEW.content_fingerprint := 'v1:' || encode(sha256(convert_to(concat_ws(chr(31),
        coalesce(NEW.claim_type, ''), coalesce(NEW.claim_scope, ''), coalesce(NEW.limitations, ''),
        coalesce(NEW.prohibited_statement, ''), coalesce(NEW.evidence_source, ''),
        coalesce(NEW.evidence_kind, ''), coalesce(NEW.source_ref, ''),
        coalesce(NEW.capability_id::text, ''), coalesce(NEW.goal_id::text, ''),
        coalesce(NEW.course_pattern, ''), coalesce(NEW.result_horizon, ''),
        coalesce(NEW.variability_note, '')
    ), 'UTF8')), 'hex');
    IF NEW.status = 'approved' THEN
        IF TG_OP = 'INSERT' OR OLD.status <> 'approved' OR OLD.approved_fingerprint = ''
           OR NEW.confirmed_at IS DISTINCT FROM OLD.confirmed_at THEN
            NEW.approved_fingerprint := NEW.content_fingerprint;
        END IF;
    ELSE
        NEW.approved_fingerprint := '';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER capabilitygoallink_fingerprint
    BEFORE INSERT OR UPDATE ON services_capabilitygoallink
    FOR EACH ROW EXECUTE FUNCTION services_goal_link_fingerprint();

-- Заполнение существующих строк: запись без изменений заставляет триггер
-- посчитать отпечаток; подтверждённые принимают его как «при подтверждении».
UPDATE services_procedurecapability SET content_fingerprint = content_fingerprint;
UPDATE services_capabilitygoallink SET content_fingerprint = content_fingerprint;
"""

DROP_FINGERPRINTS = r"""
DROP TRIGGER capabilitygoallink_fingerprint ON services_capabilitygoallink;
DROP TRIGGER procedurecapability_fingerprint ON services_procedurecapability;
DROP FUNCTION services_goal_link_fingerprint();
DROP FUNCTION services_capability_fingerprint();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0052_synthetic_test_mark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitygoallink",
            name="approved_fingerprint",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="capabilitygoallink",
            name="content_fingerprint",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="procedurecapability",
            name="approved_fingerprint",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="procedurecapability",
            name="content_fingerprint",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitygoallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("content_fingerprint", models.F("approved_fingerprint")),
                    _connector="OR",
                ),
                name="capabilitygoallink_approved_content_matches_approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurecapability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("content_fingerprint", models.F("approved_fingerprint")),
                    _connector="OR",
                ),
                name="procedurecapability_approved_content_matches_approval",
            ),
        ),
        migrations.RunSQL(sql=FINGERPRINTS, reverse_sql=DROP_FINGERPRINTS),
    ]
