# Generated by Django 5.2.5 on 2026-09-10 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_tenant_address_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "caller_purpose",
                    models.CharField(
                        choices=[
                            ("internal", "Рабочий служебный токен"),
                            ("provisioning", "Токен провизионирования"),
                        ],
                        help_text="Назначение предъявленного секрета — какой сервис пришёл.",
                        max_length=32,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        help_text="Роль разрешённого субъекта, либо 'service' — у вызова от сервиса человека может не быть вовсе, и это не то же самое, что пустая роль у человека.",
                        max_length=32,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("export", "Экспорт персональных данных"),
                            ("delete", "Стирание персональных данных"),
                            ("read_context", "Чтение личного профиля"),
                            ("write_context", "Запись в личный профиль"),
                            ("erase_context", "Стирание личного профиля"),
                            ("ask_metadata", "Служебное о вопросах профиля"),
                            ("deletion_request_create", "Заявка на удаление аккаунта"),
                            ("deletion_request_read", "Чтение заявки на удаление"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "object_category",
                    models.CharField(
                        choices=[
                            ("personal_data", "Персональные данные"),
                            ("personal_context", "Личный профиль (декларации)"),
                            ("deletion_request", "Заявка на удаление аккаунта"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True, help_text="Субъект, названный вызывающим в URL."
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("allowed", "Доступ разрешён"),
                            ("denied", "Доступ отклонён"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "denial_reason",
                    models.CharField(
                        blank=True,
                        help_text="Раздельные внутренние причины отказа при одном грубом имени наружу: subject_mismatch, wrong_purpose, unknown_actor, unnamed_actor, view_misconfigured.",
                        max_length=64,
                    ),
                ),
                (
                    "actor_named",
                    models.BooleanField(
                        help_text="Назвал ли вызывающий действующий субъект. Счётчик ступени INTERNAL_SUBJECT_AUTHZ_ENFORCE живёт здесь, а не в логе: «безымянных вызовов не было» должно доказываться запросом, который считает, а не тем, что в консоли пусто."
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        blank=True,
                        help_text="Основание / номер обращения. Пусто = никто его не назвал; умолчания у этого поля нет намеренно.",
                        max_length=128,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Субъект, которым назвался вызывающий (X-External-User-ID, разрешённый БЕЗ создания строки). NULL = вызывающий не назвал никого либо назвал личность, которой у нас нет.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_data_accesses_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_data_accesses",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала доступа к персданным",
                "verbose_name_plural": "Журнал доступа к персональным данным",
                "ordering": ("-occurred_at",),
                "permissions": [
                    (
                        "view_personal_data_access_log",
                        "Может читать журнал доступа к персональным данным",
                    )
                ],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["object_id", "-occurred_at"],
                        name="privacy_aud_object__c96ff9_idx",
                    ),
                    models.Index(
                        fields=["result", "denial_reason"],
                        name="privacy_aud_result_af9495_idx",
                    ),
                    models.Index(
                        fields=["actor_named", "-occurred_at"],
                        name="privacy_aud_actor_n_2d5c44_idx",
                    ),
                ],
            },
        ),
    ]
