# Generated by Django 5.2.5 on 2026-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("export", "Экспорт персональных данных"),
                    ("delete", "Стирание персональных данных"),
                    ("read_context", "Чтение личного профиля"),
                    ("write_context", "Запись в личный профиль"),
                    ("erase_context", "Стирание личного профиля"),
                    ("ask_metadata", "Служебное о вопросах профиля"),
                    ("deletion_request_create", "Заявка на удаление аккаунта"),
                    ("deletion_request_read", "Чтение заявки на удаление"),
                    ("read_profile", "Чтение карточки пользователя"),
                ],
                max_length=32,
            ),
        ),
    ]
