# Generated by Django 5.2.5 on 2026-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_audit", "0002_drf1709_read_profile_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="denial_reason",
            field=models.CharField(
                blank=True,
                help_text="Раздельные внутренние причины отказа при одном грубом имени наружу: subject_mismatch, wrong_purpose, unknown_actor, unnamed_actor, view_misconfigured, subject_unresolved (у актора нет профиля, который называет URL — DRF-1815).",
                max_length=64,
            ),
        ),
    ]
