# Generated by Django 5.2.5 on 2026-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_audit", "0003_denial_reason_subject_unresolved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="object_category",
            field=models.CharField(
                choices=[
                    ("personal_data", "Персональные данные"),
                    ("personal_context", "Личный профиль (декларации)"),
                    ("deletion_request", "Заявка на удаление аккаунта"),
                    ("review", "Отзыв клиента"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("export", "Экспорт персональных данных"),
                    ("delete", "Стирание персональных данных"),
                    ("read_context", "Чтение личного профиля"),
                    ("write_context", "Запись в личный профиль"),
                    ("erase_context", "Стирание личного профиля"),
                    ("ask_metadata", "Служебное о вопросах профиля"),
                    ("deletion_request_create", "Заявка на удаление аккаунта"),
                    ("deletion_request_read", "Чтение заявки на удаление"),
                    ("read_profile", "Чтение карточки пользователя"),
                    ("review_create", "Отзыв клиента о визите"),
                ],
                max_length=32,
            ),
        ),
    ]
