# DRF-1803 (M11): операции журнала «чтение/запись места работы мастера».
# Переклад #469 на dev: идёт ПОСЛЕ 0007_drf1984 (в #469 была 0007 от 0006 — две
# головы графа); choices — полный набор, включая erasure_status_read.

# Generated by Django 5.2.5 on 2026-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_audit", "0007_drf1984_erasure_status_read_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("export", "Экспорт персональных данных"),
                    ("delete", "Стирание персональных данных"),
                    ("read_context", "Чтение личного профиля"),
                    ("write_context", "Запись в личный профиль"),
                    ("erase_context", "Стирание личного профиля"),
                    ("ask_metadata", "Служебное о вопросах профиля"),
                    ("deletion_request_create", "Заявка на удаление аккаунта"),
                    ("deletion_request_read", "Чтение заявки на удаление"),
                    ("read_profile", "Чтение карточки пользователя"),
                    ("review_create", "Отзыв клиента о визите"),
                    ("write_specialist_profile", "Запись профиля мастера"),
                    ("upload_media", "Загрузка фото мастера"),
                    ("delete_media", "Удаление фото мастера"),
                    ("review_read", "Чтение мастером отзывов о себе"),
                    ("erasure_status_read", "Чтение статуса стирания"),
                    ("read_service_location", "Чтение места работы мастера"),
                    ("write_service_location", "Запись места работы мастера"),
                ],
                max_length=32,
            ),
        ),
    ]
