# DRF-2619: caller_purpose «собственный токен администратора салона» (DRF-2607)
# — первая салонная дверь журнала §96: фото мастера рукой администратора.

# Generated by Django 5.2.5 on 2026-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_audit", "0008_drf1803_service_location_operations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="caller_purpose",
            field=models.CharField(
                choices=[
                    ("internal", "Рабочий служебный токен"),
                    ("provisioning", "Токен провизионирования"),
                    ("salon_admin_token", "Собственный токен администратора салона"),
                ],
                help_text="Назначение предъявленного секрета — какой сервис пришёл.",
                max_length=32,
            ),
        ),
    ]
