# DRF-2655: просмотр карточки оператором (§107, fail-closed), caller_purpose
# «команда оператора», поле operator (форма DRF-2653) и квитанция чистки PruneRun.

# Generated by Django 5.2.5 on 2026-09-29 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_audit", "0009_drf2619_salon_admin_token_caller"),
    ]

    operations = [
        migrations.CreateModel(
            name="PruneRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("operator", models.CharField(max_length=64)),
                ("retention_days", models.PositiveIntegerField()),
                (
                    "cutoff",
                    models.DateTimeField(
                        help_text="Удалены строки с occurred_at строго раньше."
                    ),
                ),
                ("matched", models.PositiveIntegerField()),
                ("deleted", models.PositiveIntegerField()),
                ("remaining", models.PositiveIntegerField()),
                ("oldest_remaining", models.DateTimeField(blank=True, null=True)),
                (
                    "code_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "verbose_name": "Чистка журнала доступа к персданным",
                "verbose_name_plural": "Чистки журнала доступа к персданным",
                "ordering": ("-occurred_at",),
                "permissions": [
                    ("view_prune_run", "Может читать квитанции чистки журнала доступа")
                ],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="personaldataaccesslog",
            name="operator",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="caller_purpose",
            field=models.CharField(
                choices=[
                    ("internal", "Рабочий служебный токен"),
                    ("provisioning", "Токен провизионирования"),
                    ("salon_admin_token", "Собственный токен администратора салона"),
                    ("operator_command", "Команда оператора на хосте"),
                ],
                help_text="Назначение предъявленного секрета — какой сервис пришёл.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="personaldataaccesslog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("export", "Экспорт персональных данных"),
                    ("delete", "Стирание персональных данных"),
                    ("read_context", "Чтение личного профиля"),
                    ("write_context", "Запись в личный профиль"),
                    ("erase_context", "Стирание личного профиля"),
                    ("ask_metadata", "Служебное о вопросах профиля"),
                    ("deletion_request_create", "Заявка на удаление аккаунта"),
                    ("deletion_request_read", "Чтение заявки на удаление"),
                    ("read_profile", "Чтение карточки пользователя"),
                    ("review_create", "Отзыв клиента о визите"),
                    ("write_specialist_profile", "Запись профиля мастера"),
                    ("upload_media", "Загрузка фото мастера"),
                    ("delete_media", "Удаление фото мастера"),
                    ("review_read", "Чтение мастером отзывов о себе"),
                    ("erasure_status_read", "Чтение статуса стирания"),
                    ("read_service_location", "Чтение места работы мастера"),
                    ("write_service_location", "Запись места работы мастера"),
                    ("operator_card_read", "Просмотр карточки человека оператором"),
                ],
                max_length=32,
            ),
        ),
    ]
