"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-fallback')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'users',
    'services',
    'appointments',
    'reviews',
    'payments',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'djangoProject.exception_handler.api_exception_handler',
    # Rate limiting — see docs/REFACTORING_PLAN.md Phase 2.2. Per-IP for
    # anonymous, per-user for authenticated, plus two scoped throttles
    # applied on expensive endpoints (auth handshake, payment creation).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',            # SMS bombing / DDoS cover for unauth'd clients
        'user': '120/min',           # Normal app usage
        'auth': '10/min',            # Scoped: login, verify-otp, social, anonymous, refresh
        'auth_sensitive': '5/min',   # Scoped: bind-phone, account-delete-with-otp
        'payment': '5/min',          # Scoped: POST /payments/create, refund
        'webhook': '100/min',        # Scoped: /payments/webhook (amplification cap)
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

UNFOLD = {
    "SITE_TITLE": "BeautyGO Admin",
    "SITE_HEADER": "BeautyGO",
    "SITE_URL": "/",
    "SITE_SYMBOL": "spa",  # Material Symbol icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "THEME": "light",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Пользователи",
                "separator": True,
                "items": [
                    {"title": "Пользователи", "icon": "person", "link": "/admin/users/user/"},
                    {"title": "Профили", "icon": "badge", "link": "/admin/users/profile/"},
                    {"title": "Мастера", "icon": "content_cut", "link": "/admin/users/specialistprofile/"},
                ],
            },
            {
                "title": "Услуги",
                "separator": True,
                "items": [
                    {"title": "Категории", "icon": "category", "link": "/admin/services/servicecategory/"},
                    {"title": "Услуги", "icon": "spa", "link": "/admin/services/service/"},
                ],
            },
            {
                "title": "Записи",
                "separator": True,
                "items": [
                    {"title": "Записи", "icon": "calendar_month", "link": "/admin/appointments/appointment/"},
                    {"title": "Платежи", "icon": "payments", "link": "/admin/appointments/payment/"},
                    {"title": "Расписание", "icon": "schedule", "link": "/admin/appointments/specialistworkinghours/"},
                    {"title": "Выходные", "icon": "event_busy", "link": "/admin/appointments/specialisttimeoff/"},
                ],
            },
            {
                "title": "Система",
                "items": [
                    {"title": "Outbox Events", "icon": "outbox", "link": "/admin/appointments/outboxevent/"},
                ],
            },
            {
                "title": "Авторизация",
                "items": [
                    {"title": "OTP коды", "icon": "pin", "link": "/admin/users/otpcode/"},
                    {"title": "Соц. аккаунты", "icon": "link", "link": "/admin/users/socialaccount/"},
                    {"title": "Устройства", "icon": "smartphone", "link": "/admin/users/devicetoken/"},
                ],
            },
        ],
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'BeautyGO API',
    'DESCRIPTION': 'REST API для платформы бронирования бьюти-услуг BeautyGO',
    'VERSION': '1.0.0',
    'SERVERS': [
        {'url': 'http://localhost:8000/api/v1', 'description': 'Development'},
        {'url': 'https://api.beautygo.ru/api/v1', 'description': 'Production'},
    ],
    'TAGS': [
        {'name': 'auth', 'description': '⚪ Аутентификация (shared)'},
        {'name': 'users', 'description': '⚪ Профиль пользователя (shared)'},
        {'name': 'specialists', 'description': '🟢 Мастера (client)'},
        {'name': 'specialists-pro', 'description': '🟣 Управление профилем мастера (pro)'},
        {'name': 'services', 'description': '⚪ Услуги и категории (shared)'},
        {'name': 'services-pro', 'description': '🟣 Управление услугами (pro)'},
        {'name': 'appointments', 'description': '⚪ Записи (shared)'},
        {'name': 'reviews', 'description': '🟢 Отзывы (client)'},
        {'name': 'payments', 'description': '🟢 Платежи (client)'},
        {'name': 'notifications', 'description': '⚪ Уведомления (shared)'},
        {'name': 'ai', 'description': '🟢 AI-ассистент (client)'},
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'users.middleware.AppTypeMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.JWTContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OTP Configuration
OTP_CODE_LENGTH = 6
OTP_EXPIRY_MINUTES = 5
OTP_RATE_LIMIT_SECONDS = 60
OTP_MAX_ATTEMPTS = 3
OTP_DEBUG_CODE = "0000"

# Booking Engine Configuration
BOOKING_COMMISSION_PERCENT = 8.0        # Platform commission (%)
BOOKING_MIN_AHEAD_MINUTES = 60          # Min booking lead time
BOOKING_MAX_AHEAD_DAYS = 60             # Max days in advance
BOOKING_SLOT_GRID_MINUTES = 30          # Slot interval grid

# SMS.RU Configuration
SMS_RU_API_ID = os.environ.get("SMS_RU_API_ID", "")
SMS_ENABLED = os.environ.get("SMS_ENABLED", "false").lower() == "true"
SMS_RU_SENDER = os.environ.get("SMS_RU_SENDER", "")  # Empty = default sender
SMS_RU_TIMEOUT = 10  # HTTP timeout in seconds

# Social Auth Provider Settings
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID") or None
APPLE_CLIENT_ID = os.environ.get("APPLE_CLIENT_ID") or None
VK_CLIENT_SECRET = os.environ.get("VK_CLIENT_SECRET") or None
YANDEX_CLIENT_ID = os.environ.get("YANDEX_CLIENT_ID") or None

# YooKassa Payment Settings
YOOKASSA_SHOP_ID = os.environ.get("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = os.environ.get("YOOKASSA_SECRET_KEY", "")
YOOKASSA_AGENT_ID = os.environ.get("YOOKASSA_AGENT_ID", "")  # Sub-account for split payments

# YooKassa webhook security.
# Comma-separated list of CIDR ranges or single IPs permitted to POST to
# /api/v1/payments/webhook/. YooKassa publishes its source IP ranges at
# https://yookassa.ru/developers/using-api/webhooks — copy the current list
# into the env var. If left empty, the view logs a warning but still
# accepts requests (acceptable in dev, risky in prod). prod.py should also
# verify the env is populated.
YOOKASSA_WEBHOOK_ALLOWED_IPS = [
    entry.strip()
    for entry in os.environ.get("YOOKASSA_WEBHOOK_ALLOWED_IPS", "").split(",")
    if entry.strip()
]
