"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-fallback')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'django_celery_beat',  # DB-backed periodic schedule storage
    'users',
    'services',
    'appointments',
    'reviews',
    'payments',
    'ai',
    'notifications',
    'nutrition',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Pagination — see core/pagination.py. Wired here so any GenericViewSet
    # / ListAPIView gets it for free; views with custom list() overrides
    # (appointments, services-pro) call core.pagination.paginated_success_response.
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.DefaultPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'djangoProject.exception_handler.api_exception_handler',
    # Rate limiting — see docs/REFACTORING_PLAN.md Phase 2.2. Per-IP for
    # anonymous, per-user for authenticated, plus two scoped throttles
    # applied on expensive endpoints (auth handshake, payment creation).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',            # SMS bombing / DDoS cover for unauth'd clients
        'user': '120/min',           # Normal app usage
        'auth': '10/min',            # Scoped: login, verify-otp, social, anonymous, refresh
        'auth_sensitive': '5/min',   # Scoped: bind-phone, account-delete-with-otp
        'payment': '5/min',          # Scoped: POST /payments/create, refund
        'webhook_payment': '100/min',  # Scoped: YooKassa /payments/webhook (amplification cap)
        'ai_chat': '30/min',         # Scoped: AI chat send/action endpoints
        'food_scan': '10/min',       # Scoped: POST /nutrition/scan (vision API cost cap)
        'food_log': '60/min',        # Scoped: POST /nutrition/food-log (no upstream cost; user typing speed)
        'nutrition_summary': '120/min',  # Scoped: GET /nutrition/summary (cheap aggregate; mobile may poll)
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

UNFOLD = {
    "SITE_TITLE": "BeautyGO Admin",
    "SITE_HEADER": "BeautyGO",
    "SITE_URL": "/",
    "SITE_SYMBOL": "spa",  # Material Symbol icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "THEME": "light",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Пользователи",
                "separator": True,
                "items": [
                    {"title": "Пользователи", "icon": "person", "link": "/admin/users/user/"},
                    {"title": "Профили", "icon": "badge", "link": "/admin/users/profile/"},
                    {"title": "Мастера", "icon": "content_cut", "link": "/admin/users/specialistprofile/"},
                ],
            },
            {
                "title": "Услуги",
                "separator": True,
                "items": [
                    {"title": "Категории", "icon": "category", "link": "/admin/services/servicecategory/"},
                    {"title": "Услуги", "icon": "spa", "link": "/admin/services/service/"},
                ],
            },
            {
                "title": "Записи",
                "separator": True,
                "items": [
                    {"title": "Записи", "icon": "calendar_month", "link": "/admin/appointments/appointment/"},
                    {"title": "Платежи", "icon": "payments", "link": "/admin/appointments/payment/"},
                    {"title": "Расписание", "icon": "schedule", "link": "/admin/appointments/specialistworkinghours/"},
                    {"title": "Выходные", "icon": "event_busy", "link": "/admin/appointments/specialisttimeoff/"},
                ],
            },
            {
                "title": "Система",
                "items": [
                    {"title": "Outbox Events", "icon": "outbox", "link": "/admin/appointments/outboxevent/"},
                ],
            },
            {
                "title": "Авторизация",
                "items": [
                    {"title": "OTP коды", "icon": "pin", "link": "/admin/users/otpcode/"},
                    {"title": "Соц. аккаунты", "icon": "link", "link": "/admin/users/socialaccount/"},
                    {"title": "Устройства", "icon": "smartphone", "link": "/admin/users/devicetoken/"},
                ],
            },
        ],
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'BeautyGO API',
    'DESCRIPTION': 'REST API для платформы бронирования бьюти-услуг BeautyGO',
    'VERSION': '1.0.0',
    'SERVERS': [
        {'url': 'http://localhost:8000/api/v1', 'description': 'Development'},
        {'url': 'https://api.beautygo.ru/api/v1', 'description': 'Production'},
    ],
    'TAGS': [
        {'name': 'auth', 'description': '⚪ Аутентификация (shared)'},
        {'name': 'users', 'description': '⚪ Профиль пользователя (shared)'},
        {'name': 'specialists', 'description': '🟢 Мастера (client)'},
        {'name': 'specialists-pro', 'description': '🟣 Управление профилем мастера (pro)'},
        {'name': 'services', 'description': '⚪ Услуги и категории (shared)'},
        {'name': 'services-pro', 'description': '🟣 Управление услугами (pro)'},
        {'name': 'appointments', 'description': '⚪ Записи (shared)'},
        {'name': 'reviews', 'description': '🟢 Отзывы (client)'},
        {'name': 'payments', 'description': '🟢 Платежи (client)'},
        {'name': 'notifications', 'description': '⚪ Уведомления (shared)'},
        {'name': 'ai', 'description': '🟢 AI-ассистент (client)'},
    ],
}

MIDDLEWARE = [
    # RequestIDMiddleware first so every other middleware + view + log
    # record sees the same correlation id.
    'users.middleware.RequestIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'users.middleware.AppTypeMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.JWTContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OTP Configuration
OTP_CODE_LENGTH = 6
OTP_EXPIRY_MINUTES = 5
OTP_RATE_LIMIT_SECONDS = 60
OTP_MAX_ATTEMPTS = 3
OTP_DEBUG_CODE = "0000"

# Booking Engine Configuration
BOOKING_COMMISSION_PERCENT = 8.0        # Platform commission (%)
BOOKING_MIN_AHEAD_MINUTES = 60          # Min booking lead time
BOOKING_MAX_AHEAD_DAYS = 60             # Max days in advance
BOOKING_SLOT_GRID_MINUTES = 30          # Slot interval grid

# SMS.RU Configuration
SMS_RU_API_ID = os.environ.get("SMS_RU_API_ID", "")
SMS_ENABLED = os.environ.get("SMS_ENABLED", "false").lower() == "true"
SMS_RU_SENDER = os.environ.get("SMS_RU_SENDER", "")  # Empty = default sender
SMS_RU_TIMEOUT = 10  # HTTP timeout in seconds

# Social Auth Provider Settings
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID") or None
APPLE_CLIENT_ID = os.environ.get("APPLE_CLIENT_ID") or None
VK_CLIENT_SECRET = os.environ.get("VK_CLIENT_SECRET") or None
YANDEX_CLIENT_ID = os.environ.get("YANDEX_CLIENT_ID") or None

# OpenAI / LLM. api.openai.com is geo-blocked from RU; the deployed
# environments tunnel via OPENAI_PROXY (HTTP/SOCKS proxy with non-RU exit
# IP). OPENAI_BASE_URL is optional — only set when routing through an
# OpenAI-compatible gateway (e.g. ProxyAPI). Empty values leave the
# OpenAI client unusable; fail-fast in prod.py mirrors the OAuth pattern.
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "")
OPENAI_PROXY = os.environ.get("OPENAI_PROXY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")

# AI Chat guardrails. Daily token cap is per-user (or per-guest-user) and
# tracked in Redis at key `ai:tokens:{user_id}:{YYYY-MM-DD}`. Anonymous
# message cap is enforced via Message.objects count, not Redis.
AI_MAX_TOKENS_PER_USER_PER_DAY = int(
    os.environ.get("AI_MAX_TOKENS_PER_USER_PER_DAY", "50000")
)
AI_ANON_MESSAGE_CAP = int(os.environ.get("AI_ANON_MESSAGE_CAP", "5"))
AI_HISTORY_WINDOW = int(os.environ.get("AI_HISTORY_WINDOW", "10"))
AI_SPECIALIST_CONTEXT_LIMIT = int(
    os.environ.get("AI_SPECIALIST_CONTEXT_LIMIT", "20")
)
AI_SPECIALIST_MIN_RATING = float(
    os.environ.get("AI_SPECIALIST_MIN_RATING", "4.0")
)

# RecommendationEngine cache TTL (seconds). 5 min per DRF-105 contract.
# Cache invalidates implicitly via filter-hash key change when client
# location / category / price filter shifts; explicit invalidation is
# overkill for an advisory ranker.
AI_REC_CACHE_TTL = int(os.environ.get("AI_REC_CACHE_TTL", "300"))

# Firebase Cloud Messaging — push delivery for both apps.
# FIREBASE_CREDENTIALS_JSON: full Service Account JSON as a string (CI
# path; GitHub Secret + .env injection). FIREBASE_CREDENTIALS_PATH: file
# path on disk (local dev path). Either resolves the same Admin SDK
# init. Empty values keep PushService in stub mode (logs only) — same
# pattern as the empty-DSN Sentry no-op.
FIREBASE_CREDENTIALS_JSON = os.environ.get("FIREBASE_CREDENTIALS_JSON", "")
FIREBASE_CREDENTIALS_PATH = os.environ.get("FIREBASE_CREDENTIALS_PATH", "")

# YooKassa Payment Settings
YOOKASSA_SHOP_ID = os.environ.get("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = os.environ.get("YOOKASSA_SECRET_KEY", "")
YOOKASSA_AGENT_ID = os.environ.get("YOOKASSA_AGENT_ID", "")  # Sub-account for split payments

# YooKassa webhook security.
# Comma-separated list of CIDR ranges or single IPs permitted to POST to
# /api/v1/payments/webhook/. YooKassa publishes its source IP ranges at
# https://yookassa.ru/developers/using-api/webhooks — copy the current list
# into the env. If left empty in dev, the view logs a warning but still
# accepts requests; prod.py refuses to start without it (matching the
# Phase 2.1 OAuth fail-fast pattern).
YOOKASSA_WEBHOOK_ALLOWED_IPS = [
    entry.strip()
    for entry in os.environ.get("YOOKASSA_WEBHOOK_ALLOWED_IPS", "").split(",")
    if entry.strip()
]

# Number of trusted reverse proxies between the public internet and Django.
# The webhook IP-allowlist check reads X-Forwarded-For at depth N from the
# right (the IP the outermost trusted proxy received the request from);
# anything earlier in XFF is client-controlled and ignored. Default 1 = a
# single nginx in front of Django. Set higher only if a CDN sits before
# nginx — getting this wrong opens spoofing (too high) or rejects real
# traffic (too low).
YOOKASSA_WEBHOOK_TRUSTED_PROXY_COUNT = int(
    os.environ.get("YOOKASSA_WEBHOOK_TRUSTED_PROXY_COUNT", "1"),
)

# Optional Basic Auth as a second authentication layer on top of the IP
# allowlist. YooKassa supports Basic Auth on webhook URLs (set in their
# dashboard under "Webhooks → URL"). When both env vars are present, the
# view rejects requests without a matching `Authorization: Basic ...`
# header — closes the gap "spoof IP within VPC → forge payment.succeeded".
# Per YooKassa docs (https://yookassa.ru/developers/using-api/webhooks),
# they do NOT HMAC-sign webhooks; IP allowlist + Basic Auth + payment
# re-fetch is the canonical defense-in-depth combination.
YOOKASSA_WEBHOOK_BASIC_AUTH_USER = os.environ.get(
    "YOOKASSA_WEBHOOK_BASIC_AUTH_USER", "",
)
YOOKASSA_WEBHOOK_BASIC_AUTH_PASS = os.environ.get(
    "YOOKASSA_WEBHOOK_BASIC_AUTH_PASS", "",
)


# ----------------------------------------------------------------------------
# Food Scanner — Plan Y+ multi-vendor router (docs/FOOD_SCANNER_DECISION.md)
# ----------------------------------------------------------------------------
# Yandex Cloud Foundation Models — Vision provider. Used as fallback for
# OpenAI Vision (primary) when OpenAI 5xx / timeout / low-confidence.
# Yandex serves from RU jurisdiction → 152-ФЗ-friendly path. Provision
# the API key + folder via Yandex Cloud console; both must be present
# for the provider to come online (else it raises ProviderUnavailable).
YANDEX_VISION_API_KEY = os.environ.get("YANDEX_VISION_API_KEY", "")
YANDEX_VISION_FOLDER_ID = os.environ.get("YANDEX_VISION_FOLDER_ID", "")

# Router primary / fallback vendor selection. Slice 2 will read these.
# Keep names lowercase short tokens so env diffs stay readable.
FOOD_SCANNER_PRIMARY = os.environ.get("FOOD_SCANNER_PRIMARY", "openai")
FOOD_SCANNER_FALLBACK = os.environ.get("FOOD_SCANNER_FALLBACK", "yandex")

# Nutrition summary defaults — per Notion API Spec v2.0 §FOOD SCANNER+NUTRITION
# GET /nutrition/summary. UserPersonalContext doesn't carry per-user goals
# yet (DRF-174 reduced scope) so the daily summary uses these flat defaults.
# Override at the env level if a particular pilot wants different anchors.
NUTRITION_DEFAULT_CALORIES_GOAL = int(os.environ.get("NUTRITION_DEFAULT_CALORIES_GOAL", "2000"))
NUTRITION_DEFAULT_WATER_GOAL_ML = int(os.environ.get("NUTRITION_DEFAULT_WATER_GOAL_ML", "2000"))


# ----------------------------------------------------------------------------
# Async tasks — Celery + Redis (PR3 — Phase 2 Lane A)
# ----------------------------------------------------------------------------
#
# Single REDIS_URL drives both the broker (db 0) and the cache (db 1).
# Splitting into two DBs prevents Celery state and cache evictions from
# stepping on each other under load. Self-hosted Redis on the dev VPS
# (per project owner, 2026-04-25); managed migration is a future option.
#
# CELERY_TASK_ALWAYS_EAGER=True runs every task synchronously in the
# caller's process. Tests turn it on; dev defaults to True for the same
# reason (no separate worker process needed for routine work). Set the
# env to False locally when explicitly testing async flows.

REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")

CELERY_BROKER_URL = f"{REDIS_URL}/0"
CELERY_RESULT_BACKEND = f"{REDIS_URL}/0"
CELERY_TASK_ALWAYS_EAGER = (
    os.environ.get("CELERY_TASK_ALWAYS_EAGER", "False").lower() == "true"
)
CELERY_TASK_EAGER_PROPAGATES = True            # in eager mode, fail loud
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Default PersistentScheduler reads ``CELERY_BEAT_SCHEDULE`` directly
# from settings, so the outbox dispatcher activates with zero
# DB-side bootstrap. DatabaseScheduler from django_celery_beat would
# require a one-time PeriodicTask + IntervalSchedule row creation
# (it does not autosync the Python dict) — switch to it later when
# we want runtime schedule edits via Django Admin.
CELERY_BEAT_SCHEDULE = {
    "dispatch-outbox-events": {
        "task": "appointments.tasks.dispatch_outbox_events",
        "schedule": 10.0,                       # every 10 seconds
    },
    # 1h reminder beat. Window logic in the task itself absorbs the
    # 5-min jitter so we don't spam-send if a tick arrives early/late.
    "dispatch-appointment-reminders": {
        "task": "notifications.dispatch_appointment_reminders",
        "schedule": 300.0,                      # every 5 minutes
    },
}

# Django default cache → Redis (db 1). SlotCacheService and any future
# `cache.set` / `cache.get` go through here. With this in place
# throttle counters become process-wide instead of per-worker.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,          # cache outage degrades, not fails
            "SOCKET_CONNECT_TIMEOUT": 2,
            "SOCKET_TIMEOUT": 2,
        },
        "KEY_PREFIX": "ayla",
    },
}
DJANGO_REDIS_IGNORE_EXCEPTIONS = True


# ----------------------------------------------------------------------------
# Observability (PR2 — Phase 2 Lane A)
# ----------------------------------------------------------------------------
#
# Sentry SDK is wired here unconditionally; the call is a no-op when
# SENTRY_DSN is empty (dev / CI default), so the same code path runs in
# every environment. Don't move this to prod.py — staging deploys benefit
# from Sentry too, and the no-op fallback keeps it inert until a DSN is
# provisioned.

SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT", "development")
SENTRY_TRACES_SAMPLE_RATE = float(
    os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.1"),
)
SENTRY_RELEASE = os.environ.get("SENTRY_RELEASE") or None

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    def _sentry_traces_sampler(sampling_context):
        # Health endpoints get hit every few seconds by load balancers — they
        # would dominate the trace quota and tell us nothing useful.
        request = sampling_context.get("wsgi_environ") or {}
        path = request.get("PATH_INFO", "")
        if path.startswith("/api/v1/health"):
            return 0.0
        return SENTRY_TRACES_SAMPLE_RATE

    def _sentry_before_send(event, hint):
        # send_default_pii=False already strips Authorization headers,
        # session cookies, and POST body for login forms. This hook is for
        # forward compatibility — if we ever add a custom field that
        # legitimately appears in events but legally cannot leave Russia
        # (e.g. memory-arch sensitive flags), filter it here. Today: no-op.
        return event

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        send_default_pii=False,                    # 152-ФЗ — no client PII to Sentry
        traces_sampler=_sentry_traces_sampler,
        before_send=_sentry_before_send,
        integrations=[DjangoIntegration()],
    )


# Structured logging.
#
# Two output formats: human-readable (dev/local) and JSON (prod / staging).
# The format is a setting flip rather than a code branch — dev.py and
# prod.py override LOGGING_FORMATTER below to pick which one is active.
# All log records carry the current X-Request-ID via the RequestIDFilter
# (added by users.middleware) so every line traces back to one request.

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOGGING_FORMATTER = os.environ.get("LOG_FORMAT", "human")  # "human" or "json"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "core.log_filters.RequestIDFilter",
        },
    },
    "formatters": {
        "human": {
            "format": (
                "%(asctime)s [%(levelname)s] [req=%(request_id)s] "
                "%(name)s: %(message)s"
            ),
        },
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": (
                "%(asctime)s %(levelname)s %(name)s %(request_id)s "
                "%(message)s %(pathname)s %(lineno)d"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": LOGGING_FORMATTER,
            "filters": ["request_id"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        # Quiet Django framework chatter at INFO.
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",        # we already log 4xx/5xx via DRF handler
            "propagate": False,
        },
        # App loggers — let them inherit root level (settable via LOG_LEVEL).
        "appointments": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "users": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "payments": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "reviews": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "services": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        # Pre-wire celery — PR3 starts firing tasks immediately.
        "celery": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
