# Generated by Django 5.2.5 on 2026-04-26 13:39

import django.db.models.deletion
import nutrition.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=nutrition.models._scan_image_path)),
                ('dish_name', models.CharField(blank=True, default='', max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('portion_g', models.FloatField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('nutrition', models.JSONField(blank=True, null=True)),
                ('provider_used', models.CharField(blank=True, choices=[('openai', 'OpenAI Vision'), ('yandex', 'Yandex Vision'), ('vit-self-host', 'Self-host ViT')], default='', max_length=24)),
                ('provider_fallback_from', models.CharField(blank=True, default='', help_text='If the primary provider failed, which one was tried first.', max_length=24)),
                ('latency_ms', models.IntegerField(default=0)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Scan',
                'verbose_name_plural': 'Food Scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='nutrition_f_user_id_7fb1a0_idx'), models.Index(fields=['provider_used'], name='nutrition_f_provide_6bd26b_idx')],
            },
        ),
    ]
