# Generated by Django 5.2.5 on 2026-04-29 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=200)),
                ('portion_multiplier', models.FloatField(default=1.0)),
                ('calories', models.FloatField(default=0.0)),
                ('protein_g', models.FloatField(default=0.0)),
                ('fat_g', models.FloatField(default=0.0)),
                ('carbs_g', models.FloatField(default=0.0)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=16)),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_logs', to='nutrition.foodscan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Log',
                'verbose_name_plural': 'Food Logs',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', '-logged_at'], name='nutrition_f_user_id_8a596c_idx')],
            },
        ),
    ]
