# Generated by Django 5.2.5 on 2026-04-29 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_foodlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_ml', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Log',
                'verbose_name_plural': 'Water Logs',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', '-logged_at'], name='nutrition_w_user_id_79ba99_idx')],
            },
        ),
    ]
