# Generated by Django 5.2.5 on 2026-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_waterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-provided UUID for duplicate prevention.', max_length=100, null=True, unique=True),
        ),
    ]
