# Generated by Django 5.2.5 on 2026-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_foodscan_tenant_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_ru', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('water', 'Вода'), ('tea', 'Чай'), ('coffee', 'Кофе'), ('juice', 'Сок'), ('soda', 'Газировка'), ('milk', 'Молочное'), ('alcohol', 'Алкоголь'), ('broth', 'Бульон'), ('sport', 'Спортивное'), ('other', 'Прочее')], max_length=16)),
                ('water_coefficient', models.FloatField(help_text='Доля от объёма, идущая в гидратацию. 1.0 = вода. Может быть отрицательной для крепкого алкоголя.')),
                ('kcal_per_100ml', models.FloatField(default=0.0)),
                ('protein_g_per_100ml', models.FloatField(default=0.0)),
                ('fat_g_per_100ml', models.FloatField(default=0.0)),
                ('carbs_g_per_100ml', models.FloatField(default=0.0)),
                ('sugar_g_per_100ml', models.FloatField(default=0.0)),
                ('caffeine_mg_per_100ml', models.FloatField(default=0.0)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('default_serving_ml', models.PositiveIntegerField(default=250)),
                ('default_serving_label', models.CharField(default='стакан', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beverage',
                'verbose_name_plural': 'Beverages',
                'ordering': ['category', 'name_ru'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='nutrition_b_categor_18d24f_idx')],
            },
        ),
    ]
