# Generated by Django 5.2.5 on 2026-05-04 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_beverage'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('ml', models.PositiveIntegerField()),
                ('water_ml', models.FloatField()),
                ('kcal', models.FloatField(default=0.0)),
                ('protein_g', models.FloatField(default=0.0)),
                ('fat_g', models.FloatField(default=0.0)),
                ('carbs_g', models.FloatField(default=0.0)),
                ('sugar_g', models.FloatField(default=0.0)),
                ('caffeine_mg', models.FloatField(default=0.0)),
                ('milestone_threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='UUID5(user, ts, ml, slug) — POST /water/ dedup.', max_length=100, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, choices=[('user_undo', 'Пользователь отменил'), ('admin', 'Удалено администратором')], default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beverage', models.ForeignKey(blank=True, help_text='Null = pure water entry (тапнули кнопку без выбора напитка).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='nutrition.beverage')),
                ('food_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_entries', to='nutrition.foodlog')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='water_entries', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Entry',
                'verbose_name_plural': 'Water Entries',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['user', '-ts'], name='nutrition_w_user_id_e7d7bf_idx'), models.Index(fields=['user', 'deleted_at'], name='nutrition_w_user_id_7a905c_idx')],
            },
        ),
    ]
