# Generated by Django 5.2.5 on 2026-05-04 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_water_entry'),
        ('tenants', '0001_initial'),
        ('users', '0008_user_specialist_tenant_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Женский'), ('male', 'Мужской')], default='', max_length=8)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('weight_range', models.CharField(blank=True, default='', help_text='"65-75" если ввели только диапазон.', max_length=16)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('activity_coefficient', models.FloatField(default=1.4)),
                ('goal', models.CharField(blank=True, choices=[('lose', 'Похудеть'), ('maintain', 'Поддерживать'), ('gain', 'Набрать'), ('tone', 'Подтянуть')], default='', max_length=12)),
                ('pace', models.CharField(blank=True, choices=[('gentle', 'Мягкий'), ('moderate', 'Средний')], default='', max_length=12)),
                ('diet_preference', models.CharField(blank=True, default='none', max_length=32)),
                ('health_flags', models.JSONField(blank=True, default=dict)),
                ('bmr', models.PositiveIntegerField(default=0)),
                ('daily_kcal', models.PositiveIntegerField(default=0)),
                ('daily_protein_g', models.PositiveSmallIntegerField(default=0)),
                ('daily_fat_g', models.PositiveSmallIntegerField(default=0)),
                ('daily_carbs_g', models.PositiveSmallIntegerField(default=0)),
                ('daily_water_ml', models.PositiveIntegerField(default=0)),
                ('goal_overridden_by', models.CharField(blank=True, default='', max_length=24)),
                ('bmi_warning_overridden_at', models.DateTimeField(blank=True, null=True)),
                ('last_overrides_applied', models.JSONField(blank=True, default=list)),
                ('disclaimer_acked', models.JSONField(blank=True, null=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('first_food_logged_at', models.DateTimeField(blank=True, null=True)),
                ('weekly_summary_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_profiles', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Nutrition Profile',
                'verbose_name_plural': 'Nutrition Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileIdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='nutrition_p_expires_28b311_idx')],
            },
        ),
    ]
