# Generated by Django 5.2.5 on 2026-05-04 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_nutrition_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('profile_updated', 'Профиль обновлён'), ('water_logged', 'Записан напиток'), ('milestone_reached', 'Milestone достигнут'), ('pattern_detected', 'Паттерн обнаружен'), ('recognition_completed', 'Распознавание завершено')], max_length=32)),
                ('external_user_id', models.CharField(help_text='bot:NNN form — receiver scopes incoming events by this.', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает доставки'), ('delivered', 'Доставлено'), ('dlq', 'Dead-letter (не доставлено)')], default='pending', max_length=12)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nutrition Outbox Event',
                'verbose_name_plural': 'Nutrition Outbox Events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='nutrition_n_status_2d147f_idx'), models.Index(fields=['topic', 'external_user_id'], name='nutrition_n_topic_654e60_idx')],
            },
        ),
    ]
