# Generated by Django 5.2.5 on 2026-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_nutrition_outbox_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='calcium_mg_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='fiber_g_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='iron_mg_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='magnesium_mg_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='omega3_g_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='vitamin_b12_mcg_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='vitamin_c_mg_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='vitamin_d_iu_per_100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='calcium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='fiber_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='iron_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='magnesium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='micronutrients_source',
            field=models.CharField(choices=[('usda_full', 'USDA full data'), ('usda_partial', 'USDA partial'), ('rospotrebnadzor', 'Скурихин-Тутельян'), ('ai_estimate', 'Estimated by LLM'), ('unknown', 'No data')], default='unknown', help_text="Where the row's vitamins/minerals came from. Track E pattern engine reads this to filter low-quality data.", max_length=20),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='omega3_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_b12_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_c_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_d_iu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='calcium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='fiber_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='iron_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='magnesium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='omega3_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='vitamin_b12_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='vitamin_c_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='vitamin_d_iu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
