# Generated by Django 5.2.5 on 2026-05-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_micronutrients'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDAFoodCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.PositiveIntegerField(help_text='USDA FoodData Central ID (foundation, branded, etc).', unique=True)),
                ('description', models.CharField(max_length=300)),
                ('search_key', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField(help_text='Parsed nutrient profile (kcal/protein/.../iron_mg per 100g).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'USDA Food Cache',
                'verbose_name_plural': 'USDA Food Cache',
                'indexes': [models.Index(fields=['search_key'], name='nutrition_u_search__ee9ea1_idx')],
            },
        ),
    ]
