# Generated by Django 5.2.5 on 2026-05-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_tenant_fk'),
        ('nutrition', '0011_cross_domain_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossdomainshownrule',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_domain_attributions', to='appointments.appointment'),
        ),
    ]
