# Generated by Django 5.2.5 on 2026-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # B-3 cumulative chain: 0010 (DRF-260) → 0011 (DRF-261 USDA cache)
        # → 0012 (this — RDA norms on NutritionProfile).
        ('nutrition', '0011_usda_food_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_calcium_mg',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_fiber_g',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_iron_mg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_magnesium_mg',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_omega3_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_vitamin_b12_mcg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_vitamin_c_mg',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='daily_vitamin_d_iu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
