# Generated by Django 5.2.5 on 2026-05-05 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # B-3 cumulative chain: 0010 (DRF-260) → 0011 (DRF-261 USDA cache)
        # → 0012 (DRF-265 RDA norms) → 0013 (this — CrossDomainRule).
        ('appointments', '0004_appointment_tenant_fk'),
        ('nutrition', '0012_profile_micronutrient_norms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDomainRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.SlugField(max_length=128, unique=True)),
                ('nutrition_trigger', models.CharField(help_text='Pattern slug from detect_patterns (e.g. low_vitamin_d).', max_length=64)),
                ('service_category_slug', models.CharField(help_text='ServiceCategory.slug the rule recommends.', max_length=64)),
                ('service_modifier', models.CharField(blank=True, default='', help_text="Optional sub-tag like 'argan_oil' for matching.", max_length=128)),
                ('insight_text_template', models.TextField()),
                ('rationale_text', models.TextField()),
                ('disclaimer_text', models.TextField()),
                ('min_data_points', models.PositiveSmallIntegerField(default=3, help_text='Pattern must have ≥N data points before we activate.')),
                ('cooldown_rule_days', models.PositiveSmallIntegerField(default=30)),
                ('cooldown_trigger_days', models.PositiveSmallIntegerField(default=14)),
                ('cooldown_category_days', models.PositiveSmallIntegerField(default=7)),
                ('skip_extend_days', models.PositiveSmallIntegerField(default=7)),
                ('double_skip_pause_days', models.PositiveSmallIntegerField(default=60)),
                ('excluded_health_flags', models.JSONField(blank=True, default=list)),
                ('legal_reviewed', models.BooleanField(default=False)),
                ('legal_review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('requires_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cross-Domain Rule',
                'verbose_name_plural': 'Cross-Domain Rules',
                'indexes': [models.Index(fields=['nutrition_trigger', 'is_active'], name='nutrition_c_nutriti_4622c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrossDomainShownRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nutrition_trigger', models.CharField(max_length=64)),
                ('service_category_slug', models.CharField(max_length=64)),
                ('shown_at', models.DateTimeField()),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('surface', models.CharField(choices=[('bot', 'MAX Bot'), ('mobile', 'Mobile app')], max_length=12)),
                ('user_action', models.CharField(choices=[('none', 'No action'), ('dismissed', 'Dismissed'), ('paused_7d', 'Paused 7 days'), ('converted', 'Converted to booking'), ('explained', 'Asked Откуда ты знаешь')], default='none', max_length=16)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_domain_attributions', to='appointments.appointment')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shown_rules', to='nutrition.crossdomainrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_domain_shown', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross-Domain Shown Rule',
                'verbose_name_plural': 'Cross-Domain Shown Rules',
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['user', '-shown_at'], name='nutrition_c_user_id_13d3c3_idx'), models.Index(fields=['user', 'rule'], name='nutrition_c_user_id_d1d437_idx'), models.Index(fields=['user', 'nutrition_trigger'], name='nutrition_c_user_id_e6790a_idx'), models.Index(fields=['user', 'service_category_slug'], name='nutrition_c_user_id_49358a_idx')],
            },
        ),
    ]
