# Generated by Django 5.2.5 on 2026-05-07 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_lb8_appointment_set_null'),
        ('tenants', '0002_rename_tenants_ten_is_acti_2c1ec7_idx_tenants_ten_is_acti_c80453_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodscan',
            index=models.Index(fields=['tenant', '-created_at'], name='fs_tenant_created_idx'),
        ),
    ]
