# Generated by Django 5.2.5 on 2026-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0015_foodscan_fs_tenant_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionprofile",
            name="targets_computed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда посчитан действующий ориентир. NULL — не считался либо считался до введения этих полей.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="targets_input_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Входы, из которых посчитан ориентир, на момент расчёта (§85: те же входы и версия дают тот же результат). Лежит ЗДЕСЬ, в одной строке с параметрами тела, намеренно: при отзыве согласия на расчёт (§92 п.4) удалять надо обе копии, а копию в той же строке невозможно забыть.",
            ),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="targets_method_versions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Версии методик по видам ориентира: {"calories": "mifflin_st_jeor_v1", "fluids": "adult_beverages_reference_v1"}. Словарь, а не одна строка, потому что у калорий и жидкости методики разные и меняются порознь (§85). Пустой словарь — не сохранялось.',
            ),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="targets_source",
            field=models.CharField(
                choices=[
                    ("none", "Ориентира нет"),
                    ("unknown_legacy", "Происхождение не сохранялось"),
                    ("ayla_calculated", "Рассчитано Ayla"),
                    ("user_entered", "Установлено клиентом"),
                ],
                default="none",
                help_text="Происхождение действующих ориентиров. `unknown_legacy` — названное отсутствие: посчитано до введения этих полей.",
                max_length=24,
            ),
        ),
    ]
