# Generated by Django 5.2.5 on 2026-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0018_targets_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionprofile",
            name="targets_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда человек подтвердил предложенный ориентир (§5.1). NULL — не подтверждал: ориентир либо предложен (ayla_proposed), либо его нет, либо он поставлен до введения подтверждения.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="targets_source",
            field=models.CharField(
                choices=[
                    ("none", "Ориентира нет"),
                    ("unknown_legacy", "Происхождение не сохранялось"),
                    ("ayla_proposed", "Предложено Ayla, не подтверждено"),
                    ("ayla_calculated", "Рассчитано Ayla, подтверждено"),
                    ("user_entered", "Установлено клиентом"),
                ],
                default="none",
                help_text="Происхождение действующих ориентиров. `unknown_legacy` — названное отсутствие: посчитано до введения этих полей.",
                max_length=24,
            ),
        ),
    ]
