# Generated by Django 5.2.5 on 2026-09-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0019_ayla_proposed_and_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlog",
            name="entry_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("text_estimated_confirmed", "Оценка по тексту, подтверждена"),
                    ("text_user_corrected", "Оценка по тексту, исправлена клиентом"),
                    ("photo_estimated_confirmed", "Распознано по фото, подтверждено"),
                    ("photo_user_corrected", "Распознано по фото, исправлено клиентом"),
                ],
                help_text="§136: чем получено число записи. NULL — до §136 или происхождение не передано.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Завтрак"),
                    ("lunch", "Обед"),
                    ("dinner", "Ужин"),
                    ("snack", "Перекус"),
                    ("other", "Не указан"),
                ],
                max_length=16,
            ),
        ),
    ]
