# Generated by Django 5.2.5 on 2026-09-15 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0020_food_log_entry_origin_and_meal_other"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedFoodLog",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("snapshot", models.JSONField()),
                ("deleted_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_food_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deleted Food Log (restore window)",
                "verbose_name_plural": "Deleted Food Logs (restore window)",
                "indexes": [
                    models.Index(
                        fields=["deleted_at"], name="nutrition_d_deleted_b9ab95_idx"
                    )
                ],
            },
        ),
    ]
