# Generated by Django 5.2.5 on 2026-09-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0021_deleted_food_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionprofile",
            name="calories_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда человек подтвердил ориентир по калориям (§5.1). Подтверждение — по виду, не одной кнопкой на весь набор.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="calories_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Ориентира нет"),
                    ("unknown_legacy", "Происхождение не сохранялось"),
                    ("ayla_proposed", "Предложено Ayla, не подтверждено"),
                    ("ayla_calculated", "Рассчитано Ayla, подтверждено"),
                    ("user_entered", "Установлено клиентом"),
                ],
                help_text="Происхождение ориентира по КАЛОРИЯМ. NULL — по видам не устанавливалось (строка заведена до DRF-1929); это не то же самое, что `none` («ориентира нет»).",
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="fluids_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда человек подтвердил ориентир по жидкости (§5.1). Подтверждение — по виду, не одной кнопкой на весь набор.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="fluids_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Ориентира нет"),
                    ("unknown_legacy", "Происхождение не сохранялось"),
                    ("ayla_proposed", "Предложено Ayla, не подтверждено"),
                    ("ayla_calculated", "Рассчитано Ayla, подтверждено"),
                    ("user_entered", "Установлено клиентом"),
                ],
                help_text="Происхождение ориентира по ЖИДКОСТИ. NULL — по видам не устанавливалось (строка заведена до DRF-1929); это не то же самое, что `none` («ориентира нет»).",
                max_length=24,
                null=True,
            ),
        ),
    ]
