# Generated by Django 5.2.5 on 2026-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0024_saved_meal"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodscan",
            name="provider_cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodscan",
            name="provider_usage",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
