# Generated by Django 5.2.5 on 2026-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0025_foodscan_provider_cost_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionprofile",
            name="pending_proposal",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Предложение, ожидающее подтверждения, рядом с действующим ориентиром: {kinds, values, input_snapshot, method_versions, computed_at, goal, pace, goal_overridden_by}. NULL — нет.",
                null=True,
            ),
        ),
    ]
