# Generated by Django 5.2.5 on 2026-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0026_pending_proposal_2192"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritionprofile",
            name="activity_coefficient",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
