# Generated by Django 5.2.5 on 2026-09-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0028_legacy_default_inputs_2279"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionprofile",
            name="diet_answered_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="nutritionprofile",
            name="diet_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
