# Generated by Django 5.2.5 on 2026-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0029_diet_type_2310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlog",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="carbs_g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="fat_g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="protein_g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedmeal",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
