# Generated by Django 5.2.5 on 2026-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0030_gap_not_zero_2371"),
    ]

    operations = [
        migrations.CreateModel(
            name="AICalorieEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_key", models.CharField(max_length=200, unique=True)),
                ("kcal_per_100g", models.FloatField()),
                ("model", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI Calorie Estimate",
                "verbose_name_plural": "AI Calorie Estimates",
            },
        ),
        migrations.AddField(
            model_name="foodlog",
            name="ai_calories",
            field=models.FloatField(
                blank=True,
                help_text="DRF-2761: оценка калорий ИИ на эту порцию. Не проверенное число: в `calories`, суммы и сравнение с целью не входит.",
                null=True,
            ),
        ),
    ]
