# Generated by Django 6.0.3 on 2026-04-08 10:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_alter_payment_amount'),
        ('services', '0004_service_updated_at_alter_service_duration_minutes_and_more'),
        ('users', '0003_user_guest_onboarding_anonymoussession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide client name in public listing')),
                ('specialist_reply', models.TextField(blank=True, help_text='Specialist response to this review', null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by moderation — excluded from rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.specialistprofile')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialist', 'is_hidden', '-created_at'], name='review_specialist_listing_idx'), models.Index(fields=['client'], name='review_client_idx')],
            },
        ),
    ]
