# Generated by Django 5.2.5 on 2026-05-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('tenants', '0002_rename_tenants_ten_is_acti_2c1ec7_idx_tenants_ten_is_acti_c80453_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='tenants.tenant'),
        ),
    ]
