# Generated by Django 5.2.5 on 2026-08-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_review_tenant_created_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
