# Generated by Django 6.0.3 on 2026-03-26 02:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0003_service_buffer_after_minutes'),
        ('users', '0002_specialistprofile_is_booking_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('booking.created', 'Запись создана'), ('booking.confirmed', 'Запись подтверждена'), ('booking.cancelled', 'Запись отменена'), ('booking.rescheduled', 'Запись перенесена'), ('booking.completed', 'Запись завершена'), ('booking.no_show', 'Клиент не пришёл'), ('payment.confirmed', 'Оплата подтверждена'), ('payment.refunded', 'Возврат оплаты'), ('cache.invalidate_slots', 'Инвалидация кеша слотов')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('authorized', 'Авторизован'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возвращён'), ('partially_refunded', 'Частичный возврат')], default='pending', max_length=25)),
                ('specialist_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('provider_client_secret', models.CharField(blank=True, default='', max_length=500)),
                ('last_webhook_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='SpecialistTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выходной/отпуск',
                'verbose_name_plural': 'Выходные/отпуска',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistWorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('is_working_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Рабочие часы',
                'verbose_name_plural': 'Рабочие часы',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_spec_start_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_client_status_idx',
            old_name='appointment_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_status_time_idx',
            old_name='appointment_status_start_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-provided UUID for duplicate booking prevention', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_first_visit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_duration_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_service_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_specialist_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='snapshot_timezone',
            field=models.CharField(default='Europe/Moscow', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('awaiting_payment', 'Ожидает оплаты'), ('confirmed', 'Подтверждена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Клиент не пришёл')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['specialist', 'start_datetime', 'end_datetime'], name='appt_specialist_time_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['specialist', 'status'], name='appt_specialist_status_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='specialisttimeoff',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='users.specialistprofile'),
        ),
        migrations.AddField(
            model_name='specialistworkinghours',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='users.specialistprofile'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancel_reason',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['appointment'], name='payment_appointment_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisttimeoff',
            index=models.Index(fields=['specialist', 'start_at', 'end_at'], name='time_off_specialist_range_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistworkinghours',
            index=models.Index(fields=['specialist', 'day_of_week'], name='working_hours_lookup_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialistworkinghours',
            unique_together={('specialist', 'day_of_week')},
        ),
    ]
