# Generated by Django 5.2.5 on 2026-05-07 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_tenant_fk'),
        ('services', '0008_service_tenant_servicecategory_tenant'),
        ('tenants', '0002_rename_tenants_ten_is_acti_2c1ec7_idx_tenants_ten_is_acti_c80453_idx'),
        ('users', '0009_personal_context_drf230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='appt_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', '-start_datetime'], name='appt_tenant_starttime_idx'),
        ),
    ]
