# Generated by Django 5.2.5 on 2026-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_tenant_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='bot_attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='bot_dead_lettered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='bot_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='bot_delivery_status',
            field=models.CharField(choices=[('pending', 'Ожидает доставки'), ('sent', 'Отправлено'), ('acknowledged', 'Подтверждено получателем'), ('failed', 'Ошибка доставки (ретрай возможен)'), ('dead', 'Письмо мертво (DLQ)')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='bot_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='bot_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Earliest time the publisher may retry this row.', null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='bot_response_status',
            field=models.PositiveSmallIntegerField(blank=True, help_text='HTTP status of the most recent bot-platform response.', null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='external_delivery_enabled',
            field=models.BooleanField(default=False, help_text='If False, publisher skips this row. Toggled True per topic as Block C wires each cross-service event into the contract.'),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='external_target',
            field=models.CharField(default='bot-platform', help_text='Logical destination identifier. ``bot-platform`` for the ADR-0009 cross-service ingest; future targets may be added.', max_length=64),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='local_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When local Ayla handlers finished. Cross-service delivery tracked separately via bot_delivery_status.', null=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='topic',
            field=models.CharField(choices=[('booking.created', 'Запись создана'), ('booking.confirmed', 'Запись подтверждена'), ('booking.cancelled', 'Запись отменена'), ('booking.rescheduled', 'Запись перенесена'), ('booking.completed', 'Запись завершена'), ('booking.no_show', 'Клиент не пришёл'), ('payment.confirmed', 'Оплата подтверждена'), ('payment.refunded', 'Возврат оплаты'), ('cache.invalidate_slots', 'Инвалидация кеша слотов'), ('tenant.relationship.revoked', 'TenantUserRelationship отозван (#246 Q1)')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['external_delivery_enabled', 'bot_delivery_status', 'bot_next_retry_at'], name='outbox_publisher_scan_idx'),
        ),
    ]
