# Generated by Django 5.2.5 on 2026-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_b1_payment_vocab"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
