# Generated by Django 5.2.5 on 2026-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0012_appointment_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="topic",
            field=models.CharField(
                choices=[
                    ("booking.created", "Запись создана"),
                    ("booking.confirmed", "Запись подтверждена"),
                    ("booking.cancelled", "Запись отменена"),
                    ("booking.rescheduled", "Запись перенесена"),
                    ("booking.completed", "Запись завершена"),
                    ("booking.no_show", "Клиент не пришёл"),
                    ("payment.captured", "Оплата захвачена"),
                    ("payment.failed", "Оплата не прошла"),
                    ("payment.refunded", "Возврат оплаты"),
                    ("cache.invalidate_slots", "Инвалидация кеша слотов"),
                    (
                        "tenant.relationship.revoked",
                        "TenantUserRelationship отозван (#246 Q1)",
                    ),
                    ("subscription.activated", "Подписка активирована"),
                    ("subscription.past_due", "Подписка просрочена"),
                    ("billing.fee_charged", "Комиссия за запись начислена"),
                ],
                max_length=50,
            ),
        ),
    ]
