# Generated by Django 5.2.5 on 2026-07-21 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0013_alter_outboxevent_topic"),
        ("services", "0014_alter_service_aftercare_text"),
        ("tenants", "0003_seed_default_tenants"),
        ("users", "0015_alter_specialistprofile_yclients_staff_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="salon_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salon_appointments",
                to="services.salonservice",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="services.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("salon_service__isnull", True), ("service__isnull", False)
                    ),
                    models.Q(
                        ("salon_service__isnull", False), ("service__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="appointment_exactly_one_service_source",
            ),
        ),
    ]
