# Generated by Django 5.2.5 on 2026-08-02 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0014_appointment_salon_service_alter_appointment_service_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="topic",
            field=models.CharField(
                choices=[
                    ("booking.created", "Запись создана"),
                    ("booking.confirmed", "Запись подтверждена"),
                    ("booking.cancelled", "Запись отменена"),
                    ("booking.rescheduled", "Запись перенесена"),
                    ("appointment.rescheduled", "Запись перенесена (canonical)"),
                    ("booking.completed", "Запись завершена"),
                    ("booking.no_show", "Клиент не пришёл"),
                    ("payment.captured", "Оплата захвачена"),
                    ("payment.failed", "Оплата не прошла"),
                    ("payment.refunded", "Возврат оплаты"),
                    ("cache.invalidate_slots", "Инвалидация кеша слотов"),
                    (
                        "tenant.relationship.revoked",
                        "TenantUserRelationship отозван (#246 Q1)",
                    ),
                    ("subscription.activated", "Подписка активирована"),
                    ("subscription.past_due", "Подписка просрочена"),
                    ("billing.fee_charged", "Комиссия за запись начислена"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AppointmentRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Appointment.version AFTER this reschedule."
                    ),
                ),
                ("old_start_datetime", models.DateTimeField()),
                ("old_end_datetime", models.DateTimeField()),
                ("new_start_datetime", models.DateTimeField()),
                ("new_end_datetime", models.DateTimeField()),
                (
                    "actor_role",
                    models.CharField(
                        help_text="'client' | 'specialist' | 'system' — who initiated.",
                        max_length=20,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        default="mobile_app",
                        help_text="Request channel: 'mobile_app' | 'internal_bot' | 'system'.",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                (
                    "command_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="X-Idempotency-Key of the command that produced this revision, if any — ties the audit row back to the originating request for cross-service tracing.",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ревизия переноса записи",
                "verbose_name_plural": "Ревизии переноса записей",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appointment", "version"),
                        name="apptrevision_unique_appointment_version",
                    )
                ],
            },
        ),
    ]
