# Generated by Django 5.2.5 on 2026-08-14 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_appointment_version_alter_outboxevent_topic_and_more"),
        ("tenants", "0003_seed_default_tenants"),
        ("users", "0016_user_linked_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("is_working_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="users.specialistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исключение в графике",
                "verbose_name_plural": "Исключения в графике",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["specialist", "date"], name="sched_exception_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("specialist", "date"),
                        name="schedule_exception_unique_specialist_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_time__isnull", False),
                                ("is_working_day", True),
                                ("start_time__isnull", False),
                            ),
                            models.Q(
                                ("break_end__isnull", True),
                                ("break_start__isnull", True),
                                ("end_time__isnull", True),
                                ("is_working_day", False),
                                ("start_time__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="schedule_exception_times_match_working_flag",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("break_end__isnull", True),
                                ("break_start__isnull", True),
                            ),
                            models.Q(
                                ("break_end__isnull", False),
                                ("break_start__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="schedule_exception_break_both_or_neither",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantClosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closures",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закрытие салона",
                "verbose_name_plural": "Закрытия салона",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "date"], name="tenant_closure_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("start_time__isnull", True)),
                        fields=("tenant", "date"),
                        name="tenant_closure_unique_full_day",
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "date", "start_time"),
                        name="tenant_closure_unique_partial",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_time__isnull", True), ("start_time__isnull", True)
                            ),
                            models.Q(
                                ("end_time__isnull", False),
                                ("start_time__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="tenant_closure_times_both_or_neither",
                    ),
                ],
            },
        ),
    ]
