# Generated by Django 5.2.5 on 2026-08-15 10:10
#
# DRF-1064 — closure attribution. Purely additive: two CharFields with a
# non-null default, no backfill, no constraint. Existing rows read as
# "unattributed", which is the truth about them.
#
# Numbering note: DRF-1062 (branch feat/drf1062-schedule-frame-holes, not
# merged at the time of writing) also introduces an 0016. Whichever lands
# second renumbers and re-points `dependencies` — both are AddField-only
# against 0015, so they commute and no merge migration is needed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_appointment_version_alter_outboxevent_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who closed the visit: client | specialist | salon | system. Empty for visits closed before this field existed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="no_show_marked_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who marked the no-show: client | specialist | salon | system. Empty for rows marked before this field existed.",
                max_length=16,
            ),
        ),
    ]
