# Generated by Django 5.2.5 on 2026-08-15 10:10
#
# DRF-1064 — closure attribution. Purely additive: two CharFields with a
# non-null default, no backfill, no constraint. Existing rows read as
# "unattributed", which is the truth about them.
#
# Numbered after DRF-1062's 0016 (merged in PR #225) so the graph stays
# linear — no merge migration, single leaf.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0016_drf1062_schedule_exception_tenant_closure"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who closed the visit: client | specialist | salon | system. Empty for visits closed before this field existed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="no_show_marked_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who marked the no-show: client | specialist | salon | system. Empty for rows marked before this field existed.",
                max_length=16,
            ),
        ),
    ]
