# Generated by Django 5.2.5 on 2026-09-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0017_drf1064_closure_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("awaiting_payment", "Ожидает оплаты"),
                    ("confirmed", "Подтверждена"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                    ("no_show", "Клиент не пришёл"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
