# Generated by Django 5.2.5 on 2026-09-11 11:10
#
# §142 (DRF-1240): у SpecialistTimeOff появляется автор. Только это.
#
# makemigrations заодно предложил AlterField на Appointment.status — это
# дрейф choices, оставшийся от DRF-1120 (IN_PROGRESS убран из модели без
# миграции). На уровне БД choices ничего не меняют, к этой задаче он не
# относится, и приписывать его сюда значило бы спрятать чужой хвост под
# своим номером. Снят из этой миграции сознательно; ждёт своей.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0017_drf1064_closure_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specialisttimeoff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_offs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
