# Generated by Django 5.2.5 on 2026-09-11 14:41
#
# Слияние двух листьев графа миграций ``appointments``, появившихся на
# ``dev`` параллельными слияниями после снятия strict-очереди каталога:
# ``0018_drf1240_time_off_author`` (#340) и ``0018_state_drift_drf1128``
# (#349). Операций нет — оба листа независимы; без этой миграции любой
# ``migrate``/``pytest`` падает с «Conflicting migrations detected».
# Сторож на такой дрейф в каталоге ещё не слит (DRF-1624, #317).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0018_drf1240_time_off_author"),
        ("appointments", "0018_state_drift_drf1128"),
    ]

    operations = []
