# Generated by Django 5.2.5 on 2026-10-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0020_system_module_health_topic_drf2196"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="master_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда мастер подтвердил запись (DRF-2785). Статус не меняет.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="master_acknowledged_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Appointment.version, к которой относится подтверждение мастера. Не равна version — подтверждение было до переноса.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="topic",
            field=models.CharField(
                choices=[
                    ("booking.created", "Запись создана"),
                    ("booking.confirmed", "Запись подтверждена"),
                    ("booking.cancelled", "Запись отменена"),
                    ("booking.rescheduled", "Запись перенесена"),
                    ("appointment.rescheduled", "Запись перенесена (canonical)"),
                    ("booking.completed", "Запись завершена"),
                    ("booking.no_show", "Клиент не пришёл"),
                    ("payment.captured", "Оплата захвачена"),
                    ("payment.failed", "Оплата не прошла"),
                    ("payment.refunded", "Возврат оплаты"),
                    ("cache.invalidate_slots", "Инвалидация кеша слотов"),
                    (
                        "tenant.relationship.revoked",
                        "TenantUserRelationship отозван (#246 Q1)",
                    ),
                    ("subscription.activated", "Подписка активирована"),
                    ("subscription.past_due", "Подписка просрочена"),
                    ("billing.fee_charged", "Комиссия за запись начислена"),
                    (
                        "system.module.health.degraded",
                        "Модуль деградировал (системный сигнал)",
                    ),
                    ("booking.acknowledged", "Мастер подтвердил запись"),
                ],
                max_length=50,
            ),
        ),
    ]
