"""One-off utility: migrate dev data from local db.sqlite3 to Postgres.

This is a **developer utility**, not a Django ORM migration. It moves
the contents of a local SQLite dev database into the Postgres dev DB
exposed by ``docker-compose.dev.yml``. CI never runs this. Prod never
runs this (settings/prod.py was Postgres from day one).

Prerequisites:
  1. ``db.sqlite3`` exists in repo root with the data you want to keep.
     (After issue #420 / PR #127 it is gitignored, but local copies
     still exist for any developer who ran the project before #422.)
  2. Postgres stack is up:
        docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d db
  3. ``.env`` has POSTGRES_* vars matching the running container
     (defaults from .env.example are correct for docker-compose.dev.yml).

Run from the djangoproject root::

    DJANGO_SETTINGS_MODULE=djangoProject.settings.dev \
        python scripts/migrate_sqlite_to_postgres.py

Strategy:
  1. Confirm db.sqlite3 exists and Postgres is reachable.
  2. Inject a second connection alias ``sqlite_legacy`` at runtime
     (not persisted in settings.dev — this script is the only consumer).
  3. Apply current migrations to Postgres on the default alias.
  4. ``dumpdata --database=sqlite_legacy`` → temporary JSON file.
  5. ``loaddata --database=default`` ingests into Postgres.
  6. Verify row counts on a curated set of user-data tables match
     between the two DBs. Mismatches are printed but do not abort
     (some divergence is expected for Django-managed tables).

Excluded from dump (Django-managed; ``migrate`` already created them):
  - contenttypes.contenttype
  - auth.permission
  - admin.logentry
  - sessions.session
  - token_blacklist.outstandingtoken, token_blacklist.blacklistedtoken

Fallback if the run fails partway:
  - ``docker compose -f docker-compose.yml -f docker-compose.dev.yml down -v``
    (drops the Postgres volume), then
  - ``docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d db``
  - ``make migrate``
  - Reseed any fixtures via ``make loaddata`` or per-app management cmds.

See docs/setup/postgres-migration.md for the human-readable walkthrough.
"""
from __future__ import annotations

import os
import pathlib
import sys
import tempfile

# Tables to skip during dumpdata. Each of these is regenerated by Django
# itself on `migrate`; copying them across causes PK collisions and
# silent permission drift.
EXCLUDED_MODELS = (
    "contenttypes.contenttype",
    "auth.permission",
    "admin.logentry",
    "sessions.session",
    "token_blacklist.outstandingtoken",
    "token_blacklist.blacklistedtoken",
)

# Tables we expect to migrate; row-count parity is sanity-checked at
# the end. Not exhaustive — just the ones a typical dev cares about
# losing. Extend if you have local data in other apps.
VERIFY_MODELS = (
    "users.User",
    "users.SpecialistProfile",
    "services.Service",
    "services.ServiceCategory",
    "appointments.Appointment",
    "reviews.Review",
    "payments.Payment",
)


def _abort(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _bootstrap_django() -> None:
    """Initialise Django before importing models / settings.

    Inlined so the file is a stand-alone script (not a Django management
    command — those bind to a single settings module and we need to add
    a runtime DB alias).
    """
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "djangoProject.settings.dev")
    import django  # noqa: PLC0415 — must come after env setup
    django.setup()


def _check_sqlite(sqlite_path: pathlib.Path) -> None:
    if not sqlite_path.exists():
        _abort(
            f"{sqlite_path} not found. Nothing to migrate — either the file "
            "was already removed (issue #420) or you're running the script "
            "from the wrong directory. Run from the djangoproject root."
        )
    if sqlite_path.stat().st_size == 0:
        _abort(f"{sqlite_path} is empty (0 bytes). Nothing to migrate.")


def _check_postgres() -> None:
    """Open + close a default connection to fail loud if Postgres is unreachable."""
    from django.db import connections  # noqa: PLC0415
    try:
        conn = connections["default"]
        conn.ensure_connection()
        with conn.cursor() as cur:
            cur.execute("SELECT 1")
            cur.fetchone()
    except Exception as exc:  # pragma: no cover — disaster path
        _abort(
            f"Postgres unreachable on the default settings.dev connection: "
            f"{exc.__class__.__name__}: {exc}. "
            "Bring the stack up first: docker compose -f docker-compose.yml "
            "-f docker-compose.dev.yml up -d db"
        )


def _inject_sqlite_alias(sqlite_path: pathlib.Path) -> None:
    """Add a 'sqlite_legacy' DATABASES alias at runtime.

    Not written into settings.dev because (a) the alias has only one
    consumer — this script — and (b) Postgres-only is the documented
    contract of settings.dev post-#422.
    """
    from django.conf import settings  # noqa: PLC0415
    settings.DATABASES["sqlite_legacy"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(sqlite_path),
        "ATOMIC_REQUESTS": False,
        "AUTOCOMMIT": True,
        "CONN_MAX_AGE": 0,
        "OPTIONS": {},
        "TIME_ZONE": None,
        "CONN_HEALTH_CHECKS": False,
        "TEST": {"NAME": None, "CHARSET": None, "COLLATION": None, "MIRROR": None},
        "USER": "",
        "PASSWORD": "",
        "HOST": "",
        "PORT": "",
    }


def _migrate_postgres() -> None:
    """Apply current migrations to the default (Postgres) connection."""
    from django.core.management import call_command  # noqa: PLC0415
    print("Applying migrations to Postgres (default connection)...")
    call_command("migrate", "--database=default", verbosity=1, interactive=False)


def _dump_sqlite_to_json() -> pathlib.Path:
    """``manage.py dumpdata --database=sqlite_legacy`` → temp JSON file.

    Uses natural keys so the loaded data is FK-safe across PK
    renumberings (Postgres assigns sequence-based PKs that won't match
    SQLite's rowids for every row).
    """
    from django.core.management import call_command  # noqa: PLC0415
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="sqlite_to_pg_")) / "dump.json"
    print(f"Dumping SQLite data to {tmp}...")
    with tmp.open("w", encoding="utf-8") as f:
        call_command(
            "dumpdata",
            "--database=sqlite_legacy",
            "--natural-foreign",
            "--natural-primary",
            *(f"--exclude={m}" for m in EXCLUDED_MODELS),
            indent=2,
            stdout=f,
        )
    size_kb = tmp.stat().st_size / 1024
    print(f"  → {size_kb:.1f} KB dumped")
    return tmp


def _load_into_postgres(dump_path: pathlib.Path) -> None:
    from django.core.management import call_command  # noqa: PLC0415
    print(f"Loading {dump_path} into Postgres...")
    call_command("loaddata", str(dump_path), database="default")


def _verify_row_counts() -> None:
    """Compare row counts in SQLite vs Postgres for VERIFY_MODELS.

    Print-only; does not abort on mismatch. Diff might be legitimate
    (e.g. extra fixtures Postgres already had via migrate data
    operations) — caller should eyeball the table.
    """
    from django.apps import apps  # noqa: PLC0415
    print("\nRow-count verification:")
    print(f"  {'Model':40s}  {'SQLite':>8s}  {'Postgres':>8s}  diff")
    for dotted in VERIFY_MODELS:
        app_label, model_name = dotted.split(".")
        try:
            model = apps.get_model(app_label, model_name)
        except LookupError:
            print(f"  {dotted:40s}  {'-':>8s}  {'-':>8s}  (model not installed)")
            continue
        sqlite_count = model.objects.using("sqlite_legacy").count()
        pg_count = model.objects.using("default").count()
        diff = pg_count - sqlite_count
        marker = " " if diff == 0 else "*"
        print(f"  {dotted:40s}  {sqlite_count:>8d}  {pg_count:>8d}  {marker}{diff:+d}")
    print(
        "\n* non-zero diff: usually OK if Postgres had data-migration "
        "fixtures already; check by eye if anything is missing."
    )


def main() -> int:
    _bootstrap_django()

    # Repo root = parent of scripts/
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    sqlite_path = repo_root / "db.sqlite3"

    _check_sqlite(sqlite_path)
    _check_postgres()
    _inject_sqlite_alias(sqlite_path)
    _migrate_postgres()
    dump = _dump_sqlite_to_json()
    _load_into_postgres(dump)
    _verify_row_counts()

    print(
        f"\nDone. JSON dump kept at {dump} — delete after you have "
        "confirmed the data round-trip is correct."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
