# Generated by Django 5.2.5 on 2026-09-12 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendationSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_ref", models.CharField(max_length=64)),
                ("intent_id", models.CharField(max_length=64)),
                (
                    "semantic_resolution_ref",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_ref", "created_at"],
                        name="recset_subject_created_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "primary"),
                            ("alternative", "alternative"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "rerank_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALTERNATIVE_REQUESTED", "ALTERNATIVE_REQUESTED"),
                            ("REJECTED", "REJECTED"),
                            ("CONSTRAINT_ADDED", "CONSTRAINT_ADDED"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("direction_code", models.CharField(max_length=64)),
                ("target_outcomes", models.JSONField(default=list)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("ADDRESS", "ADDRESS"),
                            ("SUPPORT", "SUPPORT"),
                            ("RECOVER", "RECOVER"),
                            ("OBSERVE", "OBSERVE"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("CLEAR_PRIMARY", "CLEAR_PRIMARY"),
                            ("MULTIPLE_SUITABLE", "MULTIPLE_SUITABLE"),
                            ("INSUFFICIENT_CONTEXT", "INSUFFICIENT_CONTEXT"),
                            ("SAFETY_BOUNDARY", "SAFETY_BOUNDARY"),
                            ("NO_ACTION", "NO_ACTION"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "readiness_state",
                    models.CharField(
                        choices=[
                            ("READY", "READY"),
                            ("NEEDS_DISCRIMINATION", "NEEDS_DISCRIMINATION"),
                            ("NEEDS_REQUIRED_CONTEXT", "NEEDS_REQUIRED_CONTEXT"),
                            ("INSUFFICIENT_EVIDENCE", "INSUFFICIENT_EVIDENCE"),
                            ("BLOCKED", "BLOCKED"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_codes", models.JSONField(default=list)),
                ("evidence_refs", models.JSONField(default=list)),
                ("explanation", models.JSONField(default=dict)),
                ("safety_evaluation_ref", models.JSONField(default=dict)),
                ("consent_evaluation_ref", models.JSONField(default=dict)),
                ("context_snapshot_ref", models.JSONField(default=dict)),
                ("memory_snapshot_ref", models.JSONField(blank=True, null=True)),
                (
                    "execution_mapping_snapshot_ref",
                    models.JSONField(blank=True, null=True),
                ),
                ("transaction_snapshot_ref", models.JSONField(blank=True, null=True)),
                ("decision_policy_version", models.CharField(max_length=32)),
                ("taxonomy_version", models.CharField(max_length=32)),
                ("safety_policy_version", models.CharField(max_length=32)),
                ("catalog_mapping_version", models.CharField(max_length=32)),
                ("presentation_policy_version", models.CharField(max_length=32)),
                ("presentation_version", models.PositiveIntegerField(default=1)),
                (
                    "record_schema_version",
                    models.CharField(default="1.0", max_length=8),
                ),
                ("created_at", models.DateTimeField()),
                ("actionable_until", models.DateTimeField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="recommendation.recommendation",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="recommendation.recommendation",
                    ),
                ),
                (
                    "recommendation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="recommendation.recommendationset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("recommendation.created", "recommendation.created"),
                            ("recommendation.presented", "recommendation.presented"),
                            (
                                "recommendation.explanation_requested",
                                "recommendation.explanation_requested",
                            ),
                            (
                                "recommendation.alternative_requested",
                                "recommendation.alternative_requested",
                            ),
                            ("recommendation.engaged", "recommendation.engaged"),
                            ("booking_intent.created", "booking_intent.created"),
                        ],
                        max_length=48,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("producer", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="recommendation.recommendation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recommendation", "kind"], name="recevent_rec_kind_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["recommendation_set", "role"], name="rec_set_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["actionable_until"], name="rec_actionable_idx"),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("recommendation_set",),
                name="recommendation_one_primary_per_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("parent__isnull", True),
                        ("rerank_reason", ""),
                        ("role", "primary"),
                    ),
                    models.Q(
                        ("parent__isnull", False),
                        ("role", "alternative"),
                        models.Q(("rerank_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="recommendation_alternative_has_parent_and_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("actionable_until__gt", models.F("created_at"))),
                name="recommendation_actionable_after_created",
            ),
        ),
    ]
